CREATE TABLE ats_replication.ats_authorizations (
	authorization_id DECIMAL(38, 0) NOT NULL,
	application_accepted_date TIMESTAMP(0) NULL,
	application_received_date TIMESTAMP(0) NULL,
	application_fee DECIMAL(11, 2) NULL,
	application_egarms_receipt VARCHAR(20) NULL,
	authorization_due_date TIMESTAMP(0) NULL,
	authorization_fee DECIMAL(11, 2) NULL,
	authorization_egarms_receipt VARCHAR(20) NULL,
	amendment_renewal_date TIMESTAMP(0) NULL,
	target_days DECIMAL(38, 0) NULL,
	bring_forward_date TIMESTAMP(0) NULL,
	terms VARCHAR(500) NULL,
	agcy_representative_first_name VARCHAR(60) NULL,
	agency_representative_surname VARCHAR(60) NULL,
	value_offered_comment VARCHAR(2000) NULL,
	tenure_administration_lead VARCHAR(120) NULL,
	tech_review_completion_date TIMESTAMP(0) NULL,
	first_nation_comment VARCHAR(2000) NULL,
	first_nation_start_date TIMESTAMP(0) NULL,
	first_nation_completion_date TIMESTAMP(0) NULL,
	first_nation_consultation_lead VARCHAR(120) NULL,
	adjudication_date TIMESTAMP(0) NULL,
	fcbc_process_complete_date TIMESTAMP(0) NULL,
	authorization_status_code VARCHAR(6) NOT NULL,
	authorization_payment_type_cd VARCHAR(6) NULL,
	application_payment_type_code VARCHAR(6) NULL,
	athn_close_reason_code VARCHAR(6) NULL,
	project_id DECIMAL(38, 0) NOT NULL,
	managing_fcbc_region_id DECIMAL(38, 0) NOT NULL,
	regional_user_id DECIMAL(38, 0) NULL,
	authorization_instrument_id DECIMAL(38, 0) NOT NULL,
	application_rejected_date TIMESTAMP(0) NULL,
	authorization_target_id bigint NOT NULL,
	subregional_office_id DECIMAL(38, 0) NULL,
	secondary_office_id DECIMAL(38, 0) NULL,
	file_number VARCHAR(32) NULL,
	who_created VARCHAR(30) NOT NULL,
	when_created TIMESTAMP(0) NOT NULL,
	who_updated VARCHAR(30) NULL,
	when_updated TIMESTAMP(0) NULL
);
