-- DROP TABLE IF EXISTS lrm_replication.sv_sales_schedule;
CREATE TABLE lrm_replication.sv_sales_schedule (
    divi_div_nbr NUMERIC(2),
    divi_short_code VARCHAR(15),
    ozon_operating_zone_id VARCHAR(10),
    field_team VARCHAR(150),
    manu_id VARCHAR(60),
    opar_operating_area_name VARCHAR(30),
    licence_id VARCHAR(15),
    licn_category_id VARCHAR(10),
    linc_cert_level_id VARCHAR(10),
    term NUMERIC,
    tenure_type VARCHAR(40),
    licn_licence_state VARCHAR(20),
    registrant VARCHAR(60),
    perm_permit_id VARCHAR(40),
    geographic_location VARCHAR(4000),
    mark_mark_id VARCHAR(15),
    block_id VARCHAR(20),
    block_full_name VARCHAR(37),
    cutb_system_id VARCHAR(15),
    cutb_block_state VARCHAR(20),
    cutb_longitude VARCHAR(40),
    cutb_latitude VARCHAR(40),
    sttp_stand_type VARCHAR(40),
    cutb_vol_data_source VARCHAR(40),
    blal_merch_ha_area NUMERIC(11, 6),
    blal_harvested_ha_area NUMERIC(11, 6),
    blal_cruise_m3_vol NUMERIC(15, 6),
    rw_vol NUMERIC(15, 6),
    block_volume NUMERIC,
    blal_harvested_m3_vol NUMERIC(15, 6),
    auction_status VARCHAR(30),
    auction_date TIMESTAMP,
    auction_fiscal NUMERIC,
    auction_quarter VARCHAR(41),
    auc_quart_month VARCHAR(57),
    current_period_flag CHAR(1),
    current_period_start TIMESTAMP,
    current_period_end TIMESTAMP,
    silviculture_system VARCHAR(4000),
    yarding_system VARCHAR(4000),
    harvest_considerations VARCHAR(4000),
    piece_size NUMERIC,
    species_composition VARCHAR(4000),
    hi_status VARCHAR(30),
    hi_date TIMESTAMP,
    expire_status VARCHAR(30),
    expire_date TIMESTAMP,
    rc_status VARCHAR(30),
    rc_date VARCHAR(30),
    dr_status TIMESTAMP,
    dr_date TIMESTAMP,
    dvs_status VARCHAR(30),
    dvs_date TIMESTAMP,
    layout_status VARCHAR(30),
    layout_date TIMESTAMP,
    dvc_status VARCHAR(30),
    dvc_date TIMESTAMP,
    write_off_status VARCHAR(30),
    write_off_date TIMESTAMP,
    licn_seq_nbr NUMERIC(15),
    cutb_seq_nbr NUMERIC(16),
    objectid NUMERIC(38),
    shape TEXT
);

CREATE TABLE bctsadmin_replication.bcts_category_code (
    bcts_category_code VARCHAR(1),
    description VARCHAR(120),
    effective_date TIMESTAMP,
    expiry_date TIMESTAMP,
    update_timestamp TIMESTAMP
);
