-- DROP TABLE IF EXISTS bcts_staging.volume_advertised_official;

CREATE TABLE IF NOT EXISTS bcts_staging.volume_advertised_official
(
    business_area_region_category text COLLATE pg_catalog."default",
    business_area_region text COLLATE pg_catalog."default",
    business_area text COLLATE pg_catalog."default",
    business_area_code character varying(6) COLLATE pg_catalog."default",
    mgmt_unit_type character varying(1) COLLATE pg_catalog."default",
    mgmt_unit_id character varying(4) COLLATE pg_catalog."default",
    description character varying(120) COLLATE pg_catalog."default",
    forest_file_id character varying(10) COLLATE pg_catalog."default",
    bcts_category_code character varying(1) COLLATE pg_catalog."default",
    category character varying(120) COLLATE pg_catalog."default",
    auction_date timestamp without time zone,
    sale_volume numeric(13,1),
    fta_volume numeric(10,0),
    client_count bigint,
    eligible_client_count bigint,
    ineligible_client_count bigint,
    client_count_eligibility_indicator_missing bigint,
    no_sale_rationale_code character varying(2) COLLATE pg_catalog."default",
    no_sale_rationale text COLLATE pg_catalog."default",
    auction_date_fiscal numeric,
    auction_date_quarter text COLLATE pg_catalog."default",
    tenure_term numeric(5,0),
    initial_expiry_dt date,
    current_expiry_dt date,
    awarded_ind text COLLATE pg_catalog."default",
    file_status_st character varying(3) COLLATE pg_catalog."default",
    first_auction_date timestamp without time zone,
    last_auction_date timestamp without time zone,
    auction_count bigint,
    first_auction text COLLATE pg_catalog."default",
    last_auction text COLLATE pg_catalog."default",
    last_auction_no_sale text COLLATE pg_catalog."default",
    report_start_date date,
    report_end_date date,
    fiscal_year numeric,
    report_run_date DATE DEFAULT CURRENT_DATE
)
