-- DROP TABLE IF EXISTS bcts_staging.volume_advertised_main_hist;

CREATE TABLE IF NOT EXISTS bcts_staging.volume_advertised_main_hist
(
    business_area_region_category text COLLATE pg_catalog."default",
    business_area_region text COLLATE pg_catalog."default",
    business_area text COLLATE pg_catalog."default",
    business_area_code character varying(6) COLLATE pg_catalog."default",
    mgmt_unit_type character varying(1) COLLATE pg_catalog."default",
    mgmt_unit_id character varying(4) COLLATE pg_catalog."default",
    nav_name character varying(60) COLLATE pg_catalog."default",
    district_name character varying(60) COLLATE pg_catalog."default",
    field_team character varying(150) COLLATE pg_catalog."default",
    geographiclocation character varying(4000) COLLATE pg_catalog."default",
    operatingarea text COLLATE pg_catalog."default",
    description character varying(120) COLLATE pg_catalog."default",
    forest_file_id character varying(10) COLLATE pg_catalog."default",
    bcts_category_code character varying(1) COLLATE pg_catalog."default",
    category character varying(120) COLLATE pg_catalog."default",
    auction_date timestamp without time zone,
    auction_date_fiscal numeric,
    auction_date_quarter text COLLATE pg_catalog."default",
    lrm_auction_date timestamp without time zone,
    lrm_auction_status character varying(30) COLLATE pg_catalog."default",
    sale_volume numeric(13,1),
    fta_volume numeric(10,0),
    lrm_total_volume numeric,
    lrm_cruise_volume numeric,
    lrm_rw_volume numeric,
    lrm_total_volume_salvage_all_fire_years numeric,
    lrm_total_volume_salvage_2021_fire numeric,
    lrm_total_volume_salvage_2022_fire numeric,
    lrm_total_volume_salvage_2023_fire numeric,
    lrm_total_volume_salvage_2024_fire numeric,
    client_count bigint,
    eligible_client_count bigint,
    ineligible_client_count bigint,
    client_count_eligibility_indicator_missing bigint,
    file_status_st character varying(3) COLLATE pg_catalog."default",
    awarded_ind text COLLATE pg_catalog."default",
    no_sale_rationale_code character varying(2) COLLATE pg_catalog."default",
    no_sale_rationale text COLLATE pg_catalog."default",
    lrm_auc_fiscal numeric,
    lrm_auc_quarter text COLLATE pg_catalog."default",
    first_auction_date timestamp without time zone,
    last_auction_date timestamp without time zone,
    auction_count bigint,
    first_auction text COLLATE pg_catalog."default",
    last_auction text COLLATE pg_catalog."default",
    last_auction_no_sale text COLLATE pg_catalog."default",
    report_start_date date,
    report_end_date date,
    fiscal_year numeric,
    report_run_date DATE DEFAULT CURRENT_DATE
)
