-- DROP TABLE IF EXISTS bcts_staging.licence_issued_with_unbilled_volume_hist;

CREATE TABLE IF NOT EXISTS bcts_staging.licence_issued_with_unbilled_volume_hist
(
    business_area_region_category text COLLATE pg_catalog."default",
    business_area_region text COLLATE pg_catalog."default",
    business_area text COLLATE pg_catalog."default",
    field_team text COLLATE pg_catalog."default",
    licence_id character varying(10) COLLATE pg_catalog."default",
    tenure_type_fta character varying(3) COLLATE pg_catalog."default",
    cruise_based_ind character varying(1) COLLATE pg_catalog."default",
    fta_file_status text COLLATE pg_catalog."default",
    client_number character varying(8) COLLATE pg_catalog."default",
    client text COLLATE pg_catalog."default",
    fta_file_status_date timestamp(0) without time zone,
    legal_effective_date_fta date,
    legal_effective_fiscal_fta text COLLATE pg_catalog."default",
    issued_done_lrm timestamp without time zone,
    issued_done_fiscal_lrm text COLLATE pg_catalog."default",
    initial_expiry_fta date,
    current_expiry_fta date,
    expiry_fta date,
    expire_extend_lrm timestamp without time zone,
    advertised_licence_term integer,
    extension_term numeric,
    total_tenure_term numeric,
    sale_volume numeric(13,1),
    billed_volume numeric,
    unbilled_volume numeric,
    percent_unbilled numeric,
    licn_seq_nbr numeric(15,0),
    last_logging_started_date timestamp without time zone,
    last_logging_completed_date timestamp without time zone,
    harvesting_status text COLLATE pg_catalog."default",
    report_date date,
    unbilled_volume_over_20_month numeric,
    unbilled_volume_expire_in_6_month numeric,
    report_run_date date DEFAULT CURRENT_DATE
)
