CREATE OR REPLACE VIEW BCTS_STAGING.STUMPAGE_RATE_LRM AS
SELECT
    FL.LICENCE_ID AS LICENCE_ID,
    FL.TSO_NAME AS TSO_NAME,
    MAX(FA.ACTI_VARIABLE_COST_UPSET) AS ACTI_VARIABLE_COST_UPSET,
    MAX(FA.ACTI_TOTAL_COST_UPSET) AS ACTI_TOTAL_COST_UPSET,
    MAX(FA.ACTI_MPS70) AS ACTI_MPS70
FROM
    LRM_REPLICATION.V_LICENCE FL
    LEFT JOIN LRM_REPLICATION.ACTIVITY FA ON FL.LICN_SEQ_NBR = FA.LICN_SEQ_NBR
GROUP BY
    FL.LICENCE_ID,
    FL.TSO_NAME;
