CREATE TABLE lrm_replication.cut_block_shape (
    objectid NUMERIC,
    transaction_id VARCHAR(50),
    cutb_seq_nbr NUMERIC(16),
    bufferdist NUMERIC(38, 8),
    objectid_1 NUMERIC(10),
    transactio VARCHAR(50),
    objectid_2 NUMERIC(10),
    hectares NUMERIC(38, 8),
    feature_len NUMERIC(38, 8),
    feature_area NUMERIC(38, 8),
    shape_len NUMERIC(38, 8),
    shape_area NUMERIC(38, 8),
    -- shape TEXT,
    licn_seq_nbr NUMERIC(16),
    manu_seq_nbr NUMERIC(16),
    mark_seq_nbr NUMERIC(16),
    perm_seq_nbr NUMERIC(16),
    modifiedby VARCHAR(30),
    modifiedon TIMESTAMP,
    modifiedusing VARCHAR(30),
    createdby VARCHAR(30),
    createdon TIMESTAMP,
    createdusing VARCHAR(30)
);

CREATE OR REPLACE VIEW bcts_staging.forest_cut_block_shape AS
SELECT * FROM lrm_replication.cut_block_shape;


-- DROP TABLE IF EXISTS bcts_staging.old_growth_tap_deferral_categories;

-- Added to store static Old Growth TAP deferral categories (Ancient, Remnant, Big Tree) used in DIP timber inventory reporting.
-- These categories are derived from GIS analysis and do not change over time, supporting consistent dashboard reporting.

CREATE TABLE IF NOT EXISTS bcts_staging.old_growth_tap_deferral_categories
(
    ubi text COLLATE pg_catalog."default",
    ancient text COLLATE pg_catalog."default",
    remnant text COLLATE pg_catalog."default",
    big_treed text COLLATE pg_catalog."default"
)


-- DROP TABLE IF EXISTS bcts_staging.development_in_progress_hist;

CREATE TABLE IF NOT EXISTS bcts_staging.timber_inventory_development_in_progress_hist
(
    business_area_region_category text COLLATE pg_catalog."default",
    business_area_region text COLLATE pg_catalog."default",
    business_area text COLLATE pg_catalog."default",
    business_area_code character varying(15) COLLATE pg_catalog."default",
    fieldteam character varying(150) COLLATE pg_catalog."default",
    manu_id character varying(60) COLLATE pg_catalog."default",
    licence_id character varying(15) COLLATE pg_catalog."default",
    tenure_type character varying(40) COLLATE pg_catalog."default",
    perm_permit_id character varying(40) COLLATE pg_catalog."default",
    mark_mark_id character varying(15) COLLATE pg_catalog."default",
    block_id character varying(20) COLLATE pg_catalog."default",
    ubi character varying(15) COLLATE pg_catalog."default",
    block_nbr character varying(15) COLLATE pg_catalog."default",
    sub_operating_area character varying(120) COLLATE pg_catalog."default",
    licn_licence_state character varying(20) COLLATE pg_catalog."default",
    cutb_block_state character varying(20) COLLATE pg_catalog."default",
    deferred_at_report_date text COLLATE pg_catalog."default",
    inventory_category text COLLATE pg_catalog."default",
    merch_area numeric(11,6),
    cruise_volume numeric(15,6),
    rw_volume numeric(15,6),
    rc_status text COLLATE pg_catalog."default",
    rc_date date,
    rc_fiscal numeric,
    dr_status text COLLATE pg_catalog."default",
    dr_date date,
    dr_fiscal numeric,
    dvs_status text COLLATE pg_catalog."default",
    dvs_date date,
    dvs_fiscal numeric,
    dsc_status text COLLATE pg_catalog."default",
    dsc_date date,
    dvc_status text COLLATE pg_catalog."default",
    dvc_date date,
    dvc_fiscal numeric,
    days_in_dip double precision,
    days_in_dip_category text COLLATE pg_catalog."default",
    woff_status text COLLATE pg_catalog."default",
    woff_date date,
    woff_fiscal numeric,
    auc_status character varying(30) COLLATE pg_catalog."default",
    auc_date timestamp without time zone,
    hi_status character varying(30) COLLATE pg_catalog."default",
    hi_date timestamp without time zone,
    hvs_status text COLLATE pg_catalog."default",
    hvs_date date,
    hvc_status text COLLATE pg_catalog."default",
    hvc_date date,
    fg_met_status text COLLATE pg_catalog."default",
    fg_date date,
    def_change_of_op_plan_status text COLLATE pg_catalog."default",
    def_change_of_op_plan date,
    def_first_nations_status text COLLATE pg_catalog."default",
    def_first_nations date,
    def_loss_of_access_status text COLLATE pg_catalog."default",
    def_loss_of_access date,
    def_other_status text COLLATE pg_catalog."default",
    def_other date,
    def_planning_constraint_status text COLLATE pg_catalog."default",
    def_planning_constraint date,
    def_returned_to_bcts_status text COLLATE pg_catalog."default",
    def_returned_to_bcts date,
    def_stale_dated_fieldwork_status text COLLATE pg_catalog."default",
    def_stale_dated_fieldwork date,
    def_stakeholder_issue_status text COLLATE pg_catalog."default",
    def_stakeholder_issue date,
    def_environmental_stewardship_initiative_status text COLLATE pg_catalog."default",
    def_environmental_stewardship_initiative date,
    def_reactivated_status text COLLATE pg_catalog."default",
    def_reactivated date,
    old_growth_strategy_status text COLLATE pg_catalog."default",
    old_growth_strategy date,
    ogs_reactivated_forest_health_status text COLLATE pg_catalog."default",
    ogs_reactivated_forest_health date,
    ogs_reactivated_fn_proceed_status text COLLATE pg_catalog."default",
    ogs_reactivated_fn_proceed date,
    ogs_reactivated_field_verified_status text COLLATE pg_catalog."default",
    ogs_reactivated_field_verified date,
    ogs_reactivated_minor_status text COLLATE pg_catalog."default",
    ogs_reactivated_minor date,
    ogs_reactivated_road_status text COLLATE pg_catalog."default",
    ogs_reactivated_road date,
    ogs_reactivated_re_engineered_status text COLLATE pg_catalog."default",
    ogs_reactivated_re_engineered date,
    xxx_zzz_flag text COLLATE pg_catalog."default",
    spatial_flag text COLLATE pg_catalog."default",
    rc_flag text COLLATE pg_catalog."default",
    dr_flag text COLLATE pg_catalog."default",
    dvs_flag text COLLATE pg_catalog."default",
    dsc_flag text COLLATE pg_catalog."default",
    dvc_flag text COLLATE pg_catalog."default",
    count_of_blocks bigint,
    salvage_any_fire_year text COLLATE pg_catalog."default",
    salvage_fire_years text COLLATE pg_catalog."default",
    salvage_2021_fire text COLLATE pg_catalog."default",
    salvage_2022_fire text COLLATE pg_catalog."default",
    salvage_2023_fire text COLLATE pg_catalog."default",
    salvage_2024_fire text COLLATE pg_catalog."default",
    salvage_2025_fire text COLLATE pg_catalog."default",
    licn_seq_nbr bigint,
    mark_seq_nbr numeric(15,0),
    cutb_seq_nbr bigint,
    ancient text COLLATE pg_catalog."default",
    remnant text COLLATE pg_catalog."default",
    big_treed text COLLATE pg_catalog."default",
    ancient_volume numeric,
    remnant_volume numeric,
    big_treed_volume numeric,
    report_end_date date,
    report_run_date DATE DEFAULT CURRENT_DATE
)
