DO $$
DECLARE
    tables text[] := ARRAY['V_ACTIVITY_COST', 'V_APPORTIONMENT', 'V_APPR_BRIDGE_TAB_COST', 'V_APPR_CULVERT_TAB_COST', 'V_APPR_INTERNAL_RATE', 'V_APPR_MINISTRY_RATE', 'V_APPR_ROAD_TAB_COST', 'V_ATTACHMENT', 'V_BLOCK', 'V_BLOCK_ACTIVITY_ALL', 'V_BLOCK_AREA', 'V_BLOCK_CRUISE', 'V_BLOCK_CRUISE_ALL_CONI_DECI', 'V_BLOCK_DEPLETION_STAGE', 'V_BLOCK_HARVEST_METHOD', 'V_BLOCK_HARVEST_STRATEGY', 'V_BLOCK_NMAR', 'V_BLOCK_OLD', 'V_BLOCK_SPATIAL', 'V_BLOCK_TASKS_ISSUE', 'V_BLOCK_TIMBER', 'V_COASTAL_COST_SURVEY_BH', 'V_COASTAL_COST_SURVEY_ROADS', 'V_COMMITMENTS', 'V_COMMIT_TRACKING_SALE_INFO', 'V_COST_SURVEY_BRIDGES', 'V_CP', 'V_DETAILED_SITE_ASSESSMENT', 'V_ECOLOGY', 'V_ECOLOGY_SITE_SERIES', 'V_EMS_ACTION_PLAN', 'V_EMS_ACTION_PLAN_DESCR', 'V_EMS_CONTRACT', 'V_EMS_INSPECTION', 'V_EMS_INSPECTION_FREQUENCY', 'V_EMS_INSPECTION_TEST_DRILL', 'V_EMS_ISSUE', 'V_EMS_ISSUE_GOVERNMENT', 'V_EMS_ISSUE_INVESTIGATION', 'V_EMS_PLAN_VS_COMPLETE_INSP', 'V_EMS_PLAN_VS_COMPL_PREWORK', 'V_EMS_REQUIREMENT', 'V_FDU', 'V_FOREST_COMMENT', 'V_FRPA_RESULTS_STRATEGIES', 'V_GIS_ACTD', 'V_GIS_ACTD_DATES', 'V_GIS_ACTS', 'V_GIS_ACTS_STATUS', 'V_HARVESTED_BLOCK_STATUS', 'V_HARVEST_HISTORY', 'V_HARVEST_UNIT', 'V_INTERIOR_COST_SURVEY_CULV', 'V_INTERIOR_COST_SURVEY_ROADS', 'V_LICENCE', 'V_LICENCE_ACTIVITY_ALL', 'V_MARK', 'V_MARK_ACTIVITY', 'V_NON_FRPA_RESULTS_STRATEGIES', 'V_PEST_INFESTATION', 'V_PLANTING', 'V_PLANTING_SPECIES', 'V_QB_VALUATION', 'V_RIPARIAN_ZONE', 'V_ROAD', 'V_ROAD_ACTIVITY', 'V_ROAD_ACTIVITY_COST', 'V_ROAD_ACTIVITY_COST_ROW', 'V_ROAD_ACTIVITY_ROW', 'V_ROAD_AGRI_LAND_RESERVE', 'V_ROAD_ASSESSMENT', 'V_ROAD_CLASS', 'V_ROAD_COMPLETION', 'V_ROAD_CUT_BLOCK', 'V_ROAD_DEACTIVATION', 'V_ROAD_EVENT_MAPPING', 'V_ROAD_GAP_ANALYSIS', 'V_ROAD_INSPECTION', 'V_ROAD_LINEAR_STRUCT', 'V_ROAD_MAINTENANCE', 'V_ROAD_MANAGEMENT_UNIT', 'V_ROAD_MAPSHEET', 'V_ROAD_ON_BLOCK', 'V_ROAD_OP_AREA', 'V_ROAD_ORGANIC_MAT', 'V_ROAD_PERMIT', 'V_ROAD_PROV_FOREST', 'V_ROAD_RADIO', 'V_ROAD_RISK', 'V_ROAD_SECTION', 'V_ROAD_SPATIAL_META', 'V_ROAD_STATUS', 'V_ROAD_STEWARD', 'V_ROAD_STRUCTURE', 'V_ROAD_STRUCTURE_ATTR', 'V_ROAD_STRUCTURE_CULVERT', 'V_ROAD_STRUCTURE_INSPECTION', 'V_ROAD_STRUCTURE_MAINTENANCE', 'V_ROAD_USE_PERMIT', 'V_SALE_FORECAST_TKA_TEMP', 'V_SILVICULTURAL_SYSTEM', 'V_SILVICULTURE_ACTIVITY', 'V_SILVICULTURE_ACTIVITY_TEST1', 'V_SILVICULTURE_AMENDMENT', 'V_SILVICULTURE_OVERLAY_XREF', 'V_SILVICULTURE_PRESCRIPTION', 'V_SILVICULTURE_STOCKING_STATUS', 'V_SILVICULTURE_STRATUM_HISTORY', 'V_SILV_PROJECT', 'V_SILV_PROJECT_BLOCK', 'V_SILV_STOCKSTAT_HISTORY', 'V_SPECIES_COMPOSITION', 'V_SPECIES_COMPOSITION_HIST', 'V_STOCKING_STANDARD', 'V_STRATUM_STATUS', 'V_SU', 'V_SU_ECO_ALLOCATION', 'V_SU_LAYER', 'V_SU_STRATUM_ALLOCATION', 'V_THIRD_PARTY_INTEREST', 'V_TIMBER_INVENTORY_DIP'];  
    table_name text;
BEGIN
    -- Loop through the list of table names
    FOREACH table_name IN ARRAY tables
    LOOP
        INSERT INTO ods_data_management.cdc_master_table_list 
        VALUES (
            NULL,
            'lrm',
            NULL,               
            'forestview',
            table_name,               
            'lrm_replication',
            table_name,
            'Y',
            NULL,
            NULL,
            NULL,
            'Y',
            1,
            'N',
            'N',
            NULL,
            'Oracle'
        );
    END LOOP;
END $$;
