CREATE TABLE lrm_replication.activity (
    acti_seq_nbr NUMERIC(15) NOT NULL,
    cutb_seq_nbr NUMERIC(15) NULL,
    perm_seq_nbr NUMERIC(15) NULL,
    actt_seq_nbr NUMERIC(15) NOT NULL,
    ctor_seq_nbr NUMERIC(15) NULL,
    acti_status_ind VARCHAR(30) NULL,
    acti_status_date TIMESTAMP NULL,
    acti_comments VARCHAR(2000) NULL,
    acti_cost NUMERIC(15, 2) NULL,
    acti_harv_seas_id VARCHAR(40) NULL,
    acti_responsibility VARCHAR(160) NULL,
    acti_area NUMERIC(11, 6) NULL,
    acti_harvest_vol NUMERIC(15, 6) NULL,
    acti_int_reason VARCHAR(40) NULL,
    acti_target_date TIMESTAMP NULL,
    acti_fdp_reason VARCHAR(40) NULL,
    acti_target_cost NUMERIC(15, 2) NULL,
    plan_seq_nbr NUMERIC(15) NULL,
    licn_seq_nbr NUMERIC(15) NULL,
    mark_seq_nbr NUMERIC(15) NULL,
    cloc_seq_nbr NUMERIC(15) NULL,
    acti_digitized_ind VARCHAR(4) NULL,
    acti_cost_uom VARCHAR(120) NULL,
    modifiedby VARCHAR(120) NULL,
    modifiedon TIMESTAMP NULL,
    modifiedusing VARCHAR(120) NULL,
    createdby VARCHAR(120) NULL,
    createdon TIMESTAMP NULL,
    createdusing VARCHAR(120) NULL,
    documentkey NUMERIC(9) NULL,
    accl_description VARCHAR(160) NULL,
    PRIMARY KEY (acti_seq_nbr)
);

ALTER TABLE lrm_replication.activity OWNER TO bcts_etl_user;

