CREATE TABLE lrm_replication.activity_type (
    actt_seq_nbr NUMERIC(15) NOT NULL,
    accl_seq_nbr NUMERIC(15) NOT NULL,
    actt_description VARCHAR(200) NULL,
    divi_div_nbr NUMERIC(2) NOT NULL,
    actt_default_ind VARCHAR(4) NULL,
    actt_responsibility VARCHAR(160) NULL,
    actt_display_order NUMERIC(2) NULL,
    actt_key_ind VARCHAR(10) NULL,
    actt_status_ind VARCHAR(4) NULL,
    actt_date_relative VARCHAR(20) NULL,
    ctor_contractor_id VARCHAR(40) NULL,
    actt_view_level NUMERIC(2) NULL,
    actt_system_ind VARCHAR(4) NULL,
    ctor_seq_nbr NUMERIC(15) NULL,
    actt_active_ind VARCHAR(4) NOT NULL,
    actt_key_pair VARCHAR(40) NULL,
    actt_harvs_ind VARCHAR(4) NULL,
    actt_trvol_ind VARCHAR(4) NULL,
    actt_indirect_cost_ind VARCHAR(8) NULL,
    actt_default_cost NUMERIC(9, 2) NULL,
    actt_cost_uom VARCHAR(120) NULL,
    modifiedby VARCHAR(120) NULL,
    modifiedon TIMESTAMP NULL,
    modifiedusing VARCHAR(120) NULL,
    createdby VARCHAR(120) NULL,
    createdon TIMESTAMP NULL,
    createdusing VARCHAR(120) NULL,
    PRIMARY KEY (actt_seq_nbr)
);
