CREATE TABLE IF NOT EXISTS bcts_staging.timber_inventory_ready_to_develop
(
    business_area_region_category text COLLATE pg_catalog."default",
    business_area_region text COLLATE pg_catalog."default",
    business_area text COLLATE pg_catalog."default",
    business_area_code character varying(15) COLLATE pg_catalog."default",
    field_team character varying(150) COLLATE pg_catalog."default",
    nav_name character varying(60) COLLATE pg_catalog."default",
    operatingarea character varying(30) COLLATE pg_catalog."default",
    location character varying(800) COLLATE pg_catalog."default",
    tenure character varying(40) COLLATE pg_catalog."default",
    licence_id character varying(15) COLLATE pg_catalog."default",
    licence_state character varying(20) COLLATE pg_catalog."default",
    permit_id character varying(40) COLLATE pg_catalog."default",
    block_id character varying(20) COLLATE pg_catalog."default",
    ubi character varying(15) COLLATE pg_catalog."default",
    block_state character varying(20) COLLATE pg_catalog."default",
    deferred text COLLATE pg_catalog."default",
    inventory_category text COLLATE pg_catalog."default",
    cruise_vol numeric(15,6),
    rw_vol numeric(15,6),
    rc_status text COLLATE pg_catalog."default",
    rc_date date,
    dr_status text COLLATE pg_catalog."default",
    dr_date date,
    dr_fiscal numeric,
    dr_quarter numeric,
    dr_category text COLLATE pg_catalog."default",
    dvs_status text COLLATE pg_catalog."default",
    dvs_date date,
    dvc_status text COLLATE pg_catalog."default",
    dvc_date date,
    dvs_fiscal numeric,
    dvs_quarter numeric,
    def_change_of_op_plan_status text COLLATE pg_catalog."default",
    def_change_of_op_plan date,
    def_first_nations_status text COLLATE pg_catalog."default",
    def_first_nations date,
    def_loss_of_access_status text COLLATE pg_catalog."default",
    def_loss_of_access date,
    def_other_status text COLLATE pg_catalog."default",
    def_other date,
    def_planning_constraint_status text COLLATE pg_catalog."default",
    def_planning_constraint date,
    def_returned_to_bcts_status text COLLATE pg_catalog."default",
    def_returned_to_bcts date,
    def_stale_dated_fieldwork_status text COLLATE pg_catalog."default",
    def_stale_dated_fieldwork date,
    def_stakeholder_issue_status text COLLATE pg_catalog."default",
    def_stakeholder_issue date,
    def_environmental_stewardship_initiative_status text COLLATE pg_catalog."default",
    def_environmental_stewardship_initiative date,
    def_reactivated_status text COLLATE pg_catalog."default",
    def_reactivated date,
    old_growth_strategy_status text COLLATE pg_catalog."default",
    old_growth_strategy date,
    ogs_reactivated_forest_health_status text COLLATE pg_catalog."default",
    ogs_reactivated_forest_health date,
    ogs_reactivated_fn_proceed_status text COLLATE pg_catalog."default",
    ogs_reactivated_fn_proceed date,
    ogs_reactivated_field_verified_status text COLLATE pg_catalog."default",
    ogs_reactivated_field_verified date,
    ogs_reactivated_minor_status text COLLATE pg_catalog."default",
    ogs_reactivated_minor date,
    ogs_reactivated_road_status text COLLATE pg_catalog."default",
    ogs_reactivated_road date,
    ogs_reactivated_re_engineered_status text COLLATE pg_catalog."default",
    ogs_reactivated_re_engineered date,
    spatial_flag character varying(3) COLLATE pg_catalog."default",
    cutb_seq_nbr numeric(15,0),
    report_end_date date
)
