CREATE TABLE lrm_replication.operating_area (
    opar_operating_area_id VARCHAR(10) NOT NULL,
    divi_div_nbr NUMERIC(2) NOT NULL,
    opar_operating_area_name VARCHAR(30) NULL,
    ozon_operating_zone_id VARCHAR(10) NOT NULL,
    opar_seq_nbr NUMERIC(15) NOT NULL,
    opar_m3_ha_factor NUMERIC(15, 6) NULL,
    modifiedby VARCHAR(120) NULL,
    modifiedon TIMESTAMP NULL,
    modifiedusing VARCHAR(120) NULL,
    createdby VARCHAR(120) NULL,
    createdon TIMESTAMP NULL,
    createdusing VARCHAR(120) NULL,
    PRIMARY KEY (opar_seq_nbr)
);

CREATE TABLE lrm_replication.lrm_vt_commit_lic_type (
    code VARCHAR(2) NULL,
    description VARCHAR(50) NULL,
    activeflag NUMERIC(1) NULL,
    modifiedby VARCHAR(30) NULL,
    modifiedon TIMESTAMP NULL,
    modifiedusing VARCHAR(30) NULL
);

CREATE TABLE lrm_replication.permit_allocation (
    peal_seq_nbr NUMERIC(15) NOT NULL,
    perm_seq_nbr NUMERIC(15) NOT NULL,
    manu_seq_nbr NUMERIC(15) NULL,
    divi_div_nbr NUMERIC(2) NOT NULL,
    licn_seq_nbr NUMERIC(15) NULL,
    modifiedby VARCHAR(120) NULL,
    modifiedon TIMESTAMP NULL,
    modifiedusing VARCHAR(120) NULL,
    createdby VARCHAR(120) NULL,
    createdon TIMESTAMP NULL,
    createdusing VARCHAR(120) NULL,
    PRIMARY KEY (peal_seq_nbr)
);

CREATE TABLE lrm_replication.ctor_contractor_location (
    cloc_seq_nbr NUMERIC(15) NOT NULL,
    ctor_seq_nbr NUMERIC(15) NOT NULL,
    cloc_address_line1 VARCHAR(160) NULL,
    cloc_address_line2 VARCHAR(160) NULL,
    cloc_address_line3 VARCHAR(160) NULL,
    cloc_city VARCHAR(200) NULL,
    cloc_phone_number1 VARCHAR(40) NULL,
    cloc_phone_number2 VARCHAR(40) NULL,
    cloc_fax_number VARCHAR(40) NULL,
    ctry_country_code VARCHAR(40) NULL,
    prov_prov_state_code VARCHAR(40) NULL,
    cloc_postal_code VARCHAR(40) NULL,
    cloc_client_number CHAR NULL,
    cloc_client_location_code CHAR NULL,
    cloc_client_location_name VARCHAR(160) NULL,
    cloc_locn_expired_ind CHAR NULL,
    cloc_returned_mail_date TIMESTAMP NULL,
    modifiedby VARCHAR(120) NULL,
    modifiedon TIMESTAMP NULL,
    modifiedusing VARCHAR(120) NULL,
    createdby VARCHAR(120) NULL,
    createdon TIMESTAMP NULL,
    createdusing VARCHAR(120) NULL,
    PRIMARY KEY (cloc_seq_nbr)
);

CREATE TABLE lrm_replication.cut_block_silv_regime (
    cbsr_seq_nbr NUMERIC(15) NOT NULL,
    cutb_seq_nbr NUMERIC(15) NOT NULL,
    treg_seq_nbr NUMERIC(15) NULL,
    modifiedby VARCHAR(120) NULL,
    modifiedon TIMESTAMP NULL,
    modifiedusing VARCHAR(120) NULL,
    createdby VARCHAR(120) NULL,
    createdon TIMESTAMP NULL,
    createdusing VARCHAR(120) NULL
);

CREATE TABLE lrm_replication.v_res_vt_fdtm_team (
    colu_lookup_type VARCHAR(4) NOT NULL,
    colu_lookup_id VARCHAR(30) NOT NULL,
    divi_div_nbr NUMERIC(2) NOT NULL,
    colu_lookup_desc VARCHAR(150) NOT NULL,
    colu_user_defined_ind VARCHAR(4) NULL,
    colu_display_ind VARCHAR(1) NULL,
    colu_display_order NUMERIC(10) NULL
);

CREATE TABLE lrm_replication.commitment_partition (
    copa_seq_nbr NUMERIC(15) NOT NULL,
    copa_partition VARCHAR(30) NULL,
    copa_percent NUMERIC(7, 4) NULL,
    mark_seq_nbr INTEGER NULL,
    modifiedby VARCHAR(120) NULL,
    modifiedon TIMESTAMP NULL,
    modifiedusing VARCHAR(120) NULL,
    createdby VARCHAR(120) NULL,
    createdon TIMESTAMP NULL,
    createdusing VARCHAR(120) NULL,
    cutb_seq_nbr NUMERIC(15) NULL,
    copa_block_id VARCHAR(150) NULL,
    copa_cruise_m3_vol NUMERIC(9) NULL,
    copa_partition_type VARCHAR(150) NULL,
    copa_commit_m3_vol NUMERIC(9) NULL,
    copa_commit_part_percent NUMERIC(3) NULL,
    commit_seq_nbr NUMERIC(15) NULL,
    PRIMARY KEY (copa_seq_nbr)
);

CREATE TABLE lrm_replication.block_seed_zone (
    blsz_seq_nbr NUMERIC(15) NOT NULL,
    cutb_seq_nbr NUMERIC(15) NOT NULL,
    blsz_class_id VARCHAR(80) NOT NULL,
    blsz_species_id VARCHAR(40) NOT NULL,
    blsz_zone_id VARCHAR(80) NOT NULL,
    modifiedby VARCHAR(120) NULL,
    modifiedon TIMESTAMP NULL,
    modifiedusing VARCHAR(120) NULL,
    createdby VARCHAR(120) NULL,
    createdon TIMESTAMP NULL,
    createdusing VARCHAR(120) NULL,
    silp_seq_nbr NUMERIC(15) NULL,
    PRIMARY KEY (blsz_seq_nbr)
);

CREATE TABLE lrm_replication.standard_unit (
    stun_seq_nbr NUMERIC(15) NOT NULL,
    silp_seq_nbr NUMERIC(15) NOT NULL,
    stun_id VARCHAR(10) NOT NULL,
    suty_type_id VARCHAR(10) NOT NULL,
    stun_description VARCHAR(4000) NULL,
    stun_gross_ha_area NUMERIC(11, 6) NULL,
    stun_digitised_ind VARCHAR(1) NOT NULL,
    spss_seq_nbr NUMERIC(15) NULL,
    stun_critical_site_conditions VARCHAR(4000) NULL,
    stun_soil_compaction VARCHAR(60) NULL,
    stun_soil_erosion VARCHAR(60) NULL,
    stun_soil_displacement VARCHAR(60) NULL,
    stun_depth_unfavourable_min NUMERIC(13, 4) NULL,
    stun_depth_unfavourable_max NUMERIC(13, 4) NULL,
    stun_type_unfavourable VARCHAR(60) NULL,
    stun_sediment_risk VARCHAR(60) NULL,
    stun_max_disturbance NUMERIC(7, 4) NULL,
    stun_regen_date_early NUMERIC(4) NULL,
    stun_freegrow_date_early NUMERIC(4) NULL,
    stun_freegrow_date_late NUMERIC(4) NULL,
    stun_silvicultural_system_comm VARCHAR(4000) NULL,
    stun_temp_access_max_disturb NUMERIC(7, 4) NULL,
    stun_ncbr_ha_area NUMERIC(11, 6) NULL,
    stun_ncbr_digitised_ind VARCHAR(4) NOT NULL,
    stun_temp_access_bank_height NUMERIC(13, 4) NULL,
    stun_temp_access_avg_bank_hgt NUMERIC(13, 4) NULL,
    stun_temp_access_equipment VARCHAR(800) NULL,
    stun_soil_puddling VARCHAR(60) NULL,
    stun_soil_frost_heave VARCHAR(60) NULL,
    stun_soil_windthrow VARCHAR(60) NULL,
    stun_veg_comp_severity VARCHAR(60) NULL,
    stty_original_standard_type VARCHAR(40) NULL,
    stun_original_std_declare_date TIMESTAMP NULL,
    stun_wet_low_density_ind VARCHAR(4) NOT NULL,
    stun_ms_decl_comment VARCHAR(1000) NULL,
    stun_formc_postharv_prn_date TIMESTAMP NULL,
    stun_formc_regen_prn_date TIMESTAMP NULL,
    stun_formc_freegrow_prn_date TIMESTAMP NULL,
    stds_seq_nbr NUMERIC(15) NULL,
    stun_site_index NUMERIC(5) NULL,
    stun_other_perf_standards VARCHAR(4000) NULL,
    stun_pathway VARCHAR(40) NULL,
    stun_si_species VARCHAR(60) NULL,
    stun_brush_hazard VARCHAR(120) NULL,
    stun_browse_hazard VARCHAR(120) NULL,
    stun_si_source VARCHAR(120) NULL,
    stun_non_mappable_area NUMERIC(11, 6) NULL,
    stun_designation_code VARCHAR(80) NULL,
    stun_declaration_area NUMERIC(11, 6) NULL,
    stun_declaration_area_lock_ind VARCHAR(4) NULL,
    stun_prev_postharv_prn_date TIMESTAMP NULL,
    stun_prev_regen_prn_date TIMESTAMP NULL,
    stun_prev_freegrow_prn_date TIMESTAMP NULL,
    stun_objective_type CHAR NULL,
    stun_regen_obligation_ind VARCHAR(4) NOT NULL,
    modifiedby VARCHAR(120) NULL,
    modifiedon TIMESTAMP NULL,
    modifiedusing VARCHAR(120) NULL,
    createdby VARCHAR(120) NULL,
    createdon TIMESTAMP NULL,
    createdusing VARCHAR(120) NULL,
    PRIMARY KEY (stun_seq_nbr)
);

CREATE TABLE lrm_replication.apportionment (
    appo_seq_nbr NUMERIC(15) NOT NULL,
    manu_seq_nbr NUMERIC(15) NOT NULL,
    appo_tenure_type VARCHAR(120) NOT NULL,
    appo_date TIMESTAMP NOT NULL,
    appo_m3_vol NUMERIC(15, 6) NULL,
    pers_seq_nbr NUMERIC(15) NULL,
    corp_user_id VARCHAR(10) NULL,
    appo_comments VARCHAR(4000) NULL,
    modifiedby VARCHAR(120) NULL,
    modifiedon TIMESTAMP NULL,
    modifiedusing VARCHAR(120) NULL,
    createdby VARCHAR(120) NULL,
    createdon TIMESTAMP NULL,
    createdusing VARCHAR(120) NULL,
    fiyr NUMERIC(4) NULL,
    dispo_agreement VARCHAR(100) NULL,
    appo_end_date TIMESTAMP NULL,
    dispo_recv_lic_nmb VARCHAR(100) NULL,
    appo_m3_vol_prorated NUMERIC(15, 6) NULL,
    non_bcts_tenure_holder VARCHAR(100) NULL,
    fn_code VARCHAR(5) NULL,
    resources_data_ind NUMERIC(1) NULL,
    formula VARCHAR(150) NULL,
    PRIMARY KEY (appo_seq_nbr)
);

CREATE TABLE lrm_replication.silv_treatment_regime (
    treg_seq_nbr NUMERIC(15) NOT NULL,
    pers_seq_nbr NUMERIC(15) NULL,
    divi_div_nbr NUMERIC(2) NOT NULL,
    treg_regime_id VARCHAR(40) NOT NULL,
    treg_regime_name VARCHAR(200) NOT NULL,
    treg_create_date TIMESTAMP NOT NULL,
    treg_active_ind VARCHAR(4) NOT NULL,
    treg_def_ind VARCHAR(4) NULL,
    modifiedby VARCHAR(120) NULL,
    modifiedon TIMESTAMP NULL,
    modifiedusing VARCHAR(120) NULL,
    createdby VARCHAR(120) NULL,
    createdon TIMESTAMP NULL,
    createdusing VARCHAR(120) NULL,
    PRIMARY KEY (treg_seq_nbr)
);

CREATE TABLE lrm_replication.person (
    pers_seq_nbr NUMERIC(15) NOT NULL,
    divi_div_nbr NUMERIC(2) NOT NULL,
    pers_first_name VARCHAR(200) NULL,
    pers_last_name VARCHAR(200) NULL,
    pers_display_name VARCHAR(50) NULL,
    pers_person_number VARCHAR(20) NULL,
    pers_phone_number VARCHAR(20) NULL,
    pers_email VARCHAR(50) NULL,
    pers_fax VARCHAR(20) NULL,
    ctor_seq_nbr NUMERIC(15) NULL,
    tpct_category_id VARCHAR(40) NULL,
    tpdp_department_id VARCHAR(40) NULL,
    pers_comment VARCHAR(4000) NULL,
    pers_active_ind VARCHAR(1) NULL,
    pers_inactive_date TIMESTAMP NULL,
    pers_professional_number VARCHAR(20) NULL,
    modifiedby VARCHAR(120) NULL,
    modifiedon TIMESTAMP NULL,
    modifiedusing VARCHAR(120) NULL,
    createdby VARCHAR(120) NULL,
    createdon TIMESTAMP NULL,
    createdusing VARCHAR(120) NULL,
    PRIMARY KEY (pers_seq_nbr)
);

CREATE TABLE lrm_replication.bcts_harvest_history (
    bchh_seq_nbr NUMERIC(15) NOT NULL,
    mark_seq_nbr NUMERIC(15) NOT NULL,
    bchh_billing_year NUMERIC(4) NULL,
    bchh_billing_month NUMERIC(4) NULL,
    bchh_billing_period TIMESTAMP NULL,
    bchh_hdbs_tree_species VARCHAR(2) NULL,
    bchh_forest_product_code VARCHAR(8) NULL,
    bchh_log_grade VARCHAR(1) NULL,
    bchh_billing_type_code VARCHAR(8) NULL,
    bchh_volume_billed NUMERIC(9, 2) NULL,
    bchh_pieces_billed NUMERIC(10) NULL,
    bchh_royalty_amount NUMERIC(11, 2) NULL,
    bchh_reserve_stmpg_amt NUMERIC(9, 2) NULL,
    bchh_bonus_stumpage_amt NUMERIC(9, 2) NULL,
    bchh_silv_levy_amount NUMERIC(9, 2) NULL,
    bchh_dev_levy_amount NUMERIC(9, 2) NULL,
    bchh_update_timestamp TIMESTAMP NULL,
    bchh_update_userid VARCHAR(32) NULL,
    modifiedby VARCHAR(120) NULL,
    modifiedon TIMESTAMP NULL,
    modifiedusing VARCHAR(120) NULL,
    createdby VARCHAR(120) NULL,
    createdon TIMESTAMP NULL,
    createdusing VARCHAR(120) NULL,
    PRIMARY KEY (bchh_seq_nbr)
);

CREATE TABLE lrm_replication.commitments (
    licn_seq_nbr NUMERIC(15) NULL,
    commit_seq_nbr NUMERIC(15) NOT NULL,
    copa_partition VARCHAR(150) NULL,
    copa_commit_appo NUMERIC(15) NULL,
    modifiedby VARCHAR(30) NULL,
    modifiedon TIMESTAMP NULL,
    modifiedusing VARCHAR(30) NULL,
    createdby VARCHAR(30) NULL,
    createdon TIMESTAMP NULL,
    createdusing VARCHAR(30) NULL,
    manu_seq_nbr NUMERIC(15) NULL,
    copa_commit_lic_type VARCHAR(2) NULL,
    PRIMARY KEY (commit_seq_nbr)
);

CREATE TABLE lrm_replication.ecology_unit (
    ecou_seq_nbr NUMERIC(15) NOT NULL,
    cutb_seq_nbr NUMERIC(15) NOT NULL,
    ecou_name VARCHAR(50) NOT NULL,
    bioz_zone_id VARCHAR(10) NULL,
    bios_subzone_id VARCHAR(10) NULL,
    biov_variant_id VARCHAR(10) NULL,
    ecou_site_type_id VARCHAR(40) NULL,
    ecou_additional_info VARCHAR(160) NULL,
    ecou_ecosite_fit_code CHAR NULL,
    ecou_ha_area NUMERIC(11, 6) NOT NULL,
    ecou_digitised_ind VARCHAR(4) NULL,
    mreg_edatopic_moisture_id VARCHAR(40) NULL,
    nreg_edatopic_nutrient_id VARCHAR(40) NULL,
    ecou_elevation_min NUMERIC(5) NULL,
    ecou_elevation_max NUMERIC(5) NULL,
    ecou_elevation_avg NUMERIC(5) NULL,
    ecou_aspect VARCHAR(60) NULL,
    ecou_slope_min NUMERIC(7, 4) NULL,
    ecou_slope_max NUMERIC(7, 4) NULL,
    ecou_slope_avg NUMERIC(7, 4) NULL,
    ecou_slope_position VARCHAR(60) NULL,
    ecou_terrain VARCHAR(60) NULL,
    ecou_parent_material VARCHAR(60) NULL,
    ecou_drainage VARCHAR(60) NULL,
    ecou_substrate_decaying_wood NUMERIC(7, 4) NULL,
    ecou_substrate_bedrock NUMERIC(7, 4) NULL,
    ecou_substrate_cobbles NUMERIC(7, 4) NULL,
    ecou_substrate_mineral_soil NUMERIC(7, 4) NULL,
    ecou_substrate_organic NUMERIC(7, 4) NULL,
    ecou_substrate_water NUMERIC(7, 4) NULL,
    ecou_organic_layer VARCHAR(60) NULL,
    ecou_humus_l_depth_min NUMERIC(10, 4) NULL,
    ecou_humus_l_depth_max NUMERIC(10, 4) NULL,
    ecou_humus_f_depth_min NUMERIC(10, 4) NULL,
    ecou_humus_f_depth_max NUMERIC(10, 4) NULL,
    ecou_humus_h_depth_min NUMERIC(10, 4) NULL,
    ecou_humus_h_depth_max NUMERIC(10, 4) NULL,
    ecou_humus_form VARCHAR(60) NULL,
    ecou_soil_order VARCHAR(60) NULL,
    ecou_soil_type VARCHAR(60) NULL,
    ecou_soil_depth_water NUMERIC(10, 4) NULL,
    ecou_soil_depth_water_max NUMERIC(10, 4) NULL,
    ecou_soil_depth_mottles NUMERIC(10, 4) NULL,
    ecou_soil_depth_mottles_max NUMERIC(10, 4) NULL,
    ecou_soil_depth_gleying NUMERIC(10, 4) NULL,
    ecou_soil_depth_gleying_max NUMERIC(10, 4) NULL,
    ecou_soil_depth_calcar NUMERIC(10, 4) NULL,
    ecou_soil_depth_calcar_max NUMERIC(10, 4) NULL,
    ecou_soil_depth_bedrock NUMERIC(10, 4) NULL,
    ecou_soil_depth_bedrock_max NUMERIC(10, 4) NULL,
    ecou_soil_depth_compact NUMERIC(10, 4) NULL,
    ecou_soil_depth_compact_max NUMERIC(10, 4) NULL,
    ecou_soil_rooting_depth NUMERIC(10, 4) NULL,
    ecou_soil_seepage_ind VARCHAR(4) NULL,
    ecou_soil_seepage_depth NUMERIC(10, 4) NULL,
    ecou_soil_pit_depth NUMERIC(10, 4) NULL,
    ecou_soil_acid_test VARCHAR(4) NULL,
    ecou_soil_acid_test_depth NUMERIC(10, 4) NULL,
    ecou_soil_acid_ph_test NUMERIC(9, 6) NULL,
    ecou_soil_comments VARCHAR(4000) NULL,
    ecou_field_guide VARCHAR(160) NULL,
    ecou_field_guide_year NUMERIC(4) NULL,
    ecou_surveyed_by VARCHAR(200) NULL,
    ecou_survey_date TIMESTAMP NULL,
    ecou_comments VARCHAR(4000) NULL,
    ecou_perched_ind VARCHAR(4) NOT NULL,
    ecou_soil_acid_ph VARCHAR(40) NULL,
    bgrg_region_code VARCHAR(10) NULL,
    ecou_soil_op VARCHAR(120) NULL,
    ecou_coarse_fragment VARCHAR(120) NULL,
    modifiedby VARCHAR(120) NULL,
    modifiedon TIMESTAMP NULL,
    modifiedusing VARCHAR(120) NULL,
    createdby VARCHAR(120) NULL,
    createdon TIMESTAMP NULL,
    createdusing VARCHAR(120) NULL,
    documentkey NUMERIC(9) NULL,
    PRIMARY KEY (ecou_seq_nbr)
);

CREATE TABLE lrm_replication.sub_operating_area (
    suop_subop_area_id VARCHAR(10) NOT NULL,
    suop_subop_area_name VARCHAR(120) NOT NULL,
    divi_div_nbr NUMERIC(2) NOT NULL,
    opar_operating_area_id VARCHAR(40) NOT NULL,
    modifiedby VARCHAR(120) NULL,
    modifiedon TIMESTAMP NULL,
    modifiedusing VARCHAR(120) NULL,
    createdby VARCHAR(120) NULL,
    createdon TIMESTAMP NULL,
    createdusing VARCHAR(120) NULL,
    PRIMARY KEY (suop_subop_area_id, divi_div_nbr, opar_operating_area_id)
);

CREATE TABLE lrm_replication.mark_allocation (
    mark_seq_nbr NUMERIC(15) NOT NULL,
    divi_div_nbr NUMERIC(2) NOT NULL,
    licn_seq_nbr NUMERIC(15) NULL,
    perm_seq_nbr NUMERIC(15) NULL,
    manu_seq_nbr NUMERIC(15) NULL,
    modifiedby VARCHAR(120) NULL,
    modifiedon TIMESTAMP NULL,
    modifiedusing VARCHAR(120) NULL,
    createdby VARCHAR(120) NULL,
    createdon TIMESTAMP NULL,
    createdusing VARCHAR(120) NULL,
    maal_seq_nbr NUMERIC(15) NULL
);

CREATE TABLE lrm_replication.ctor_contractor (
    ctor_seq_nbr NUMERIC(15) NOT NULL,
    ctor_name VARCHAR(60) NOT NULL,
    ctor_email_address VARCHAR(200) NULL,
    ctor_status_code VARCHAR(8) NULL,
    ctor_internal_code VARCHAR(40) NULL,
    ctor_ems_ind VARCHAR(4) NULL,
    ctor_wcb_nbr NUMERIC(10) NULL,
    ctor_gst VARCHAR(80) NULL,
    ctor_wcb_clearance TIMESTAMP NULL,
    ctor_insurance_liability TIMESTAMP NULL,
    ctor_date_approved TIMESTAMP NULL,
    ctor_expiration_date TIMESTAMP NULL,
    ctor_approved_ind VARCHAR(4) NULL,
    ctor_comment VARCHAR(4000) NULL,
    ctor_id VARCHAR(200) NULL,
    ctor_password VARCHAR(320) NULL,
    ctor_vendor_nbr VARCHAR(40) NULL,
    ctor_post_ap_ind VARCHAR(4) NULL,
    ctor_gst_ind VARCHAR(4) NULL,
    ctor_legal_first_name VARCHAR(120) NULL,
    ctor_legal_middle_name VARCHAR(120) NULL,
    ctor_bcts_client_number VARCHAR(32) NULL,
    ctor_bcts_ocg_client_number VARCHAR(40) NULL,
    ctor_bcts_prime_mailing_locn VARCHAR(8) NULL,
    ctor_bcts_total_balance VARCHAR(56) NULL,
    ctor_birthdate TIMESTAMP NULL,
    ctor_drivers_license VARCHAR(28) NULL,
    ctor_sin VARCHAR(36) NULL,
    ctor_client_other_id VARCHAR(160) NULL,
    ctor_bcts_corp_regn_nmbr VARCHAR(36) NULL,
    ctor_bcts_corp_reporting_ind CHAR NULL,
    ctor_risky_contractor VARCHAR(4) NULL,
    ctor_rate_benefit_ind VARCHAR(4) NULL,
    modifiedby VARCHAR(120) NULL,
    modifiedon TIMESTAMP NULL,
    modifiedusing VARCHAR(120) NULL,
    createdby VARCHAR(120) NULL,
    createdon TIMESTAMP NULL,
    createdusing VARCHAR(120) NULL,
    PRIMARY KEY (ctor_seq_nbr)
);

CREATE TABLE lrm_replication.licence_allocation (
    licn_seq_nbr NUMERIC(15) NOT NULL,
    divi_div_nbr NUMERIC(2) NOT NULL,
    manu_seq_nbr NUMERIC(15) NULL,
    modifiedby VARCHAR(120) NULL,
    modifiedon TIMESTAMP NULL,
    modifiedusing VARCHAR(120) NULL,
    createdby VARCHAR(120) NULL,
    createdon TIMESTAMP NULL,
    createdusing VARCHAR(120) NULL
);

CREATE TABLE lrm_replication.silviculture_prescription (
    silp_seq_nbr NUMERIC(15) NOT NULL,
    divi_div_nbr NUMERIC(2) NOT NULL,
    cutb_seq_nbr NUMERIC(15) NOT NULL,
    silp_lterm_man_obj VARCHAR(4000) NULL,
    silp_wildlife VARCHAR(4000) NULL,
    silp_sensitive_areas VARCHAR(4000) NULL,
    silp_fisheries VARCHAR(4000) NULL,
    silp_watersheds VARCHAR(4000) NULL,
    silp_recreation VARCHAR(4000) NULL,
    silp_community_watershed_ind VARCHAR(4) NULL,
    silp_bio_diversity VARCHAR(4000) NULL,
    silp_wildlife_tree_credit_ha NUMERIC(7, 2) NULL,
    silp_visual_landscape VARCHAR(4000) NULL,
    silp_visual_assessment VARCHAR(4) NOT NULL,
    silp_cultural_heritage VARCHAR(4000) NULL,
    silp_range VARCHAR(4000) NULL,
    silp_range_tenure_holder VARCHAR(800) NULL,
    silp_other_resources VARCHAR(4000) NULL,
    silp_trapper_registration VARCHAR(200) NULL,
    silp_guide_registration VARCHAR(200) NULL,
    silp_na_conditions VARCHAR(4000) NULL,
    silp_riparian_assessment VARCHAR(4) NOT NULL,
    silp_gully_manage_strategy VARCHAR(4000) NULL,
    silp_gully_assessment VARCHAR(4) NOT NULL,
    silp_forest_health VARCHAR(4000) NULL,
    silp_pest_assessment VARCHAR(4) NOT NULL,
    silp_coarse_woody_debris VARCHAR(4000) NULL,
    silp_archaeological_sites VARCHAR(4000) NULL,
    silp_archaeology_assessment VARCHAR(4) NOT NULL,
    silp_vegetation_management VARCHAR(4000) NULL,
    silp_livestock_used VARCHAR(4) NULL,
    silp_slope_instability VARCHAR(4000) NULL,
    silp_slope_assessment VARCHAR(3) NOT NULL,
    silp_perm_access_max_pct NUMERIC(7, 4) NULL,
    silp_temp_access_max_rehab NUMERIC(10) NULL,
    silp_temp_access_max_disturb NUMERIC(7, 4) NULL,
    silp_temp_access_location VARCHAR(800) NULL,
    silp_temp_access_bank_height NUMERIC(13, 4) NULL,
    silp_temp_access_avg_bank_hgt NUMERIC(13, 4) NULL,
    silp_temp_access_equipment VARCHAR(800) NULL,
    silp_temp_access_ha_area NUMERIC(11, 6) NULL,
    silp_soil_cons_comments VARCHAR(4000) NULL,
    silp_stocking_req_comments VARCHAR(4000) NULL,
    pers_seq_nbr NUMERIC(15) NULL,
    silp_sp_report_format VARCHAR(40) NULL,
    silp_amendments_comments VARCHAR(4000) NULL,
    silp_temp_access_comments VARCHAR(4000) NULL,
    silp_riparian_comments VARCHAR(4000) NULL,
    silp_bio_diversity_calc_ind VARCHAR(4) NULL,
    silp_rpf_certify_comments VARCHAR(4000) NULL,
    silp_admin_assessment_comments VARCHAR(4000) NULL,
    silp_use_block_num_ind VARCHAR(4) NOT NULL,
    silp_coarse_woody_debris_m3_ha NUMERIC(7, 2) NULL,
    silp_bio_diversity_pct NUMERIC(3) NULL,
    silp_lichen_assessment VARCHAR(4) NULL,
    silp_roadside_disturb_max_pct NUMERIC(7, 4) NULL,
    silp_biodiv_perf_std_start_pct NUMERIC(7, 3) NULL,
    silp_bio_divers_block_tgt_pct NUMERIC(7, 3) NULL,
    silp_cwd_perf_std_pct NUMERIC(7, 3) NULL,
    silp_cwd_block_tgt_pct NUMERIC(7, 3) NULL,
    silp_perm_access_max_area NUMERIC(11, 6) NULL,
    silp_additional_comments VARCHAR(4000) NULL,
    silp_pest_required VARCHAR(4) NULL,
    silp_visual_required VARCHAR(4) NULL,
    silp_vegetation_required VARCHAR(4) NULL,
    silp_raiparian_required VARCHAR(4) NULL,
    silp_fhealth_required VARCHAR(4) NULL,
    silp_gully_required VARCHAR(4) NULL,
    silp_archeosite_required VARCHAR(4) NULL,
    silp_slope_required VARCHAR(3) NULL,
    silp_lichen_required VARCHAR(4) NULL,
    silp_forest_health_pest VARCHAR(4000) NULL,
    silp_biodiv_perf_std_end_pct NUMERIC(7, 3) NULL,
    slip_updated_by VARCHAR(200) NULL,
    slip_updated_date TIMESTAMP NULL,
    modifiedby VARCHAR(120) NULL,
    modifiedon TIMESTAMP NULL,
    modifiedusing VARCHAR(120) NULL,
    createdby VARCHAR(120) NULL,
    createdon TIMESTAMP NULL,
    createdusing VARCHAR(120) NULL,
    fspm_seq_nbr NUMERIC(15) NULL,
    PRIMARY KEY (silp_seq_nbr)
);

