CREATE TABLE lrm_replication.block_allocation (
    cutb_seq_nbr NUMERIC(15) NOT NULL,
    blal_seq_nbr NUMERIC(15) NOT NULL,
    divi_div_nbr NUMERIC(2) NOT NULL,
    licn_seq_nbr NUMERIC(15) NULL,
    perm_seq_nbr NUMERIC(15) NULL,
    mark_seq_nbr NUMERIC(15) NULL,
    blal_gross_ha_area NUMERIC(11, 6) NULL,
    blal_merch_ha_area NUMERIC(11, 6) NULL,
    blal_cruise_m3_vol NUMERIC(15, 6) NULL,
    blal_harvested_m3_vol NUMERIC(15, 6) NULL,
    blal_harvested_ha_area NUMERIC(11, 6) NULL,
    blal_firs_cutblock_id VARCHAR(80) NULL,
    blal_firs_timbermark_id VARCHAR(80) NULL,
    blal_estimated_area NUMERIC(7, 2) NULL,
    manu_seq_nbr NUMERIC(15) NULL,
    blal_digi_ind VARCHAR(1) NULL,
    blal_primary_ind VARCHAR(4) NULL,
    blal_actual_partition_vol NUMERIC(15, 2) NULL,
    blal_usr_cruise_m3_vol NUMERIC(15, 6) NULL,
    blal_rw_vol NUMERIC(15, 6) NULL,
    blal_rw_ha_area NUMERIC(11, 6) NULL,
    modifiedby VARCHAR(120) NULL,
    modifiedon TIMESTAMP NULL,
    modifiedusing VARCHAR(120) NULL,
    createdby VARCHAR(120) NULL,
    createdon TIMESTAMP NULL,
    createdusing VARCHAR(120) NULL,
    blal_data_source VARCHAR(120) NULL,
    PRIMARY KEY (blal_seq_nbr)
);

ALTER TABLE lrm_replication.block_allocation OWNER TO bcts_etl_user;
