CREATE TABLE lrm_replication.cut_block (
    cutb_seq_nbr NUMERIC(15) NOT NULL,
    cutb_block_id VARCHAR(20) NOT NULL,
    cutb_block_number VARCHAR(15) NULL,
    divi_div_nbr NUMERIC(2) NULL,
    cutb_devt_plan_status_code VARCHAR(8) NULL,
    cutb_devt_plan_apprvl_date TIMESTAMP NULL,
    cutb_silvi_plan_status_code VARCHAR(8) NULL,
    cutb_silvi_plan_apprvl_date TIMESTAMP NULL,
    cutb_block_memo VARCHAR(4000) NULL,
    cutb_woods_run_km_nbr NUMERIC(15, 6) NULL,
    cutb_hauling_km_nbr NUMERIC(15, 6) NULL,
    cutb_hlcptr_drop_cruise_ind VARCHAR(4) NULL,
    cutb_logging_plan_status_code VARCHAR(8) NULL,
    cutb_logging_plan_apprvl_date TIMESTAMP NULL,
    opar_operating_area_id VARCHAR(10) NULL,
    bioz_zone_id VARCHAR(40) NULL,
    cutb_gross_ha_area NUMERIC(11, 6) NULL,
    cutb_bcgs VARCHAR(15) NULL,
    cutb_opening VARCHAR(15) NULL,
    cutb_nts VARCHAR(60) NULL,
    cutb_ext_ha_area NUMERIC(11, 6) NULL,
    cutb_photos VARCHAR(800) NULL,
    cutb_field_work_by VARCHAR(200) NULL,
    cutb_field_work_date TIMESTAMP NULL,
    cutb_site_class VARCHAR(20) NULL,
    fdps_status_id VARCHAR(10) NULL,
    cutb_site_index NUMERIC(5) NULL,
    cutb_cpi_slope_pct NUMERIC(7, 4) NULL,
    cutb_cpi_road_access_km NUMERIC(13, 3) NULL,
    cutb_cpi_road_block_km NUMERIC(13, 3) NULL,
    cutb_cpi_road_num_landings NUMERIC(10) NULL,
    cutb_cpi_road_haul_km NUMERIC(13, 3) NULL,
    sblk_supply_block_id VARCHAR(10) NULL,
    cutb_formc_harvest_print_date TIMESTAMP NULL,
    cutb_formc_regen_print_date TIMESTAMP NULL,
    cutb_formc_freegrow_print_date TIMESTAMP NULL,
    fund_funding_code VARCHAR(15) NULL,
    cutb_highway_ind VARCHAR(1) NULL,
    cutb_winter_road_ind CHAR NULL,
    finz_forest_inventory_zone_id VARCHAR(40) NULL,
    cutb_user_mapsheet_id VARCHAR(120) NULL,
    cutb_cell_number VARCHAR(60) NULL,
    fjap_fdp_joint_approval VARCHAR(40) NULL,
    pmod_modifier_id VARCHAR(40) NULL,
    cutb_traverse_method_code VARCHAR(40) NULL,
    cutb_critical_date_ind CHAR NULL,
    cutb_greenup_date TIMESTAMP NULL,
    grns_greenup_source VARCHAR(40) NULL,
    pmpo_operating_zone VARCHAR(40) NULL,
    lsun_landscape_unit VARCHAR(40) NULL,
    plan_seq_nbr NUMERIC(15) NULL,
    cutb_forma_print_date TIMESTAMP NULL,
    cutb_block_state VARCHAR(20) NULL,
    cutb_digi_ind VARCHAR(4) NULL,
    sttp_stand_type VARCHAR(40) NULL,
    ttac_timbertype_age_class VARCHAR(40) NULL,
    ttsc_timbertype_stock_class VARCHAR(40) NULL,
    tthc_timbertype_height_class VARCHAR(40) NULL,
    cutb_site_plan_exempt_ind VARCHAR(4) NULL,
    sssc_source_code VARCHAR(40) NULL,
    cutb_vol_data_source VARCHAR(40) NULL,
    cutb_vol_data_source_type VARCHAR(16) NULL,
    cutb_heli_flight_dist NUMERIC(10) NULL,
    cutb_harvest_sequence NUMERIC(6) NULL,
    cutb_prov_forest_conflict VARCHAR(40) NULL,
    treg_seq_nbr NUMERIC(15) NULL,
    bcat_category_code VARCHAR(40) NULL,
    cutb_traverse_start_point VARCHAR(160) NULL,
    cutb_traverse_end_point VARCHAR(160) NULL,
    cutb_forma_printed VARCHAR(4) NULL,
    cutb_system_id VARCHAR(15) NULL,
    cutb_block_status VARCHAR(40) NULL,
    cutb_latitude_bak VARCHAR(40) NULL,
    cutb_longitude_bak VARCHAR(40) NULL,
    cutb_damage_type VARCHAR(40) NULL,
    cutb_opening_id NUMERIC(10) NULL,
    silp_use_block_num_ind VARCHAR(1) NOT NULL,
    cutb_location VARCHAR(800) NULL,
    cutb_silv_act_harv_link VARCHAR(120) NULL,
    cutb_file_id VARCHAR(72) NULL,
    suop_subop_area_id VARCHAR(40) NULL,
    cutb_selling_price_period TIMESTAMP NULL,
    cutb_synch_status VARCHAR(120) NULL,
    cutb_block_grouping_id VARCHAR(80) NULL,
    pers_seq_nbr NUMERIC(15) NULL,
    ctor_seq_nbr NUMERIC(15) NULL,
    cutb_variant_id VARCHAR(60) NULL,
    cutb_season_id VARCHAR(120) NULL,
    cutb_volume NUMERIC(15, 6) NULL,
    cloc_seq_nbr NUMERIC(15) NULL,
    cutb_parent_seq NUMERIC(15) NULL,
    cutb_prev_forma_print_date TIMESTAMP NULL,
    sila_seq_nbr NUMERIC(15) NULL,
    cutb_cruise_lock_ind VARCHAR(4) NULL,
    cutb_ref_dec CHAR NULL,
    cutb_reg_code VARCHAR(12) NULL,
    cutb_apr_eff_date TIMESTAMP NULL,
    siph_seq_nbr NUMERIC(15) NULL,
    cdat_seq_nbr INTEGER NULL,
    cutb_access_restriction VARCHAR(4000) NULL,
    cutb_planned_vol NUMERIC(15, 6) NULL,
    cutb_row_ind VARCHAR(4) NOT NULL,
    cutb_tim_dev_date TIMESTAMP NULL,
    cutb_ebm_ind VARCHAR(4) NULL,
    modifiedby VARCHAR(120) NULL,
    modifiedon TIMESTAMP NULL,
    modifiedusing VARCHAR(120) NULL,
    createdby VARCHAR(120) NULL,
    createdon TIMESTAMP NULL,
    createdusing VARCHAR(120) NULL,
    documentkey NUMERIC(9) NULL,
    log_start_cascade_date_ind VARCHAR(12) NULL,
    pricing_date TIMESTAMP NULL,
    cutb_latitude_dd NUMERIC(9, 6) NULL,
    cutb_longitude_dd NUMERIC(9, 6) NULL,
    cutb_latitude VARCHAR(40) NULL,
    cutb_longitude VARCHAR(40) NULL,
    marked_for_del_ind NUMERIC(1) NULL,
    marked_for_del_by VARCHAR(120) NULL,
    marked_for_del_on TIMESTAMP NULL,
    cutb_archive_reason VARCHAR(4) NULL,
    cutb_archive_date TIMESTAMP NULL,
    cutb_cprp_protection_ind VARCHAR(1) NULL,
    cutb_rc_risk_rating VARCHAR(1) NULL,
    cutb_rc_risk_source VARCHAR(5) NULL,
    cutb_rc_risk_comments VARCHAR(2000) NULL,
    operational_site_factor VARCHAR(4000) NULL,
    safety_concern VARCHAR(4000) NULL,
    PRIMARY KEY (cutb_seq_nbr)
);
