CREATE TABLE lrm_replication.cut_permit (
    perm_seq_nbr NUMERIC(15) NOT NULL,
    regn_region_id VARCHAR(10) NULL,
    perm_permit_id VARCHAR(40) NOT NULL,
    perm_revision_date TIMESTAMP NULL,
    papr_point_of_apprsl_id VARCHAR(16) NULL,
    lsee_licensee_id VARCHAR(10) NULL,
    admin_dsct_district_name VARCHAR(60) NULL,
    geo_dsct_district_name VARCHAR(240) NULL,
    perm_mgmt_unit_code VARCHAR(12) NULL,
    perm_tsb_name VARCHAR(200) NULL,
    perm_expiry_date TIMESTAMP NULL,
    perm_remote_oper_ind VARCHAR(4) NULL,
    perm_basic_silvi_ind VARCHAR(4) NULL,
    perm_road_mtce_ind VARCHAR(4) NULL,
    perm_road_land_use_chrg NUMERIC(15, 2) NULL,
    perm_cost_eff_date TIMESTAMP NULL,
    perm_rate_eff_date TIMESTAMP NULL,
    perm_water_transport_ind VARCHAR(4) NULL,
    perm_primary_block_seq_nbr NUMERIC(15) NULL,
    perm_primary_mark_id VARCHAR(40) NULL,
    perm_haul_ind VARCHAR(4) NULL,
    tsar_tsa_nbr NUMERIC(3) NULL,
    sblk_supply_block_id VARCHAR(40) NULL,
    sptc_support_centre_name VARCHAR(50) NULL,
    divi_div_nbr NUMERIC(2) NULL,
    perm_damage_status VARCHAR(20) NULL,
    perm_support_centre_dist NUMERIC(6, 2) NULL,
    opty_opening_type_id VARCHAR(40) NULL,
    pers_seq_nbr NUMERIC(15) NULL,
    perm_permit_state VARCHAR(80) NULL,
    perm_logprod_external_ind VARCHAR(4) NULL,
    perm_logprod_customer_id VARCHAR(60) NULL,
    perm_cruise_res_source VARCHAR(4) NULL,
    perm_jurisdiction VARCHAR(40) NULL,
    perm_application_description VARCHAR(4000) NULL,
    perm_primary_species VARCHAR(40) NULL,
    mkme_marking_method_code VARCHAR(40) NULL,
    mkin_marking_instrument_code VARCHAR(40) NULL,
    perm_prov_forest_conflict VARCHAR(40) NULL,
    perm_cruise_based_ind VARCHAR(40) NULL,
    perm_lsee_representative NUMERIC(15) NULL,
    perm_traverse_start_point VARCHAR(160) NULL,
    perm_traverse_end_point VARCHAR(160) NULL,
    perm_digi_ind VARCHAR(4) NULL,
    perm_bdt_conversion NUMERIC(15, 7) NULL,
    cpcl_permit_class VARCHAR(40) NULL,
    perm_parent_permit NUMERIC(15) NULL,
    perm_spuc VARCHAR(40) NULL,
    perm_salvage_ind VARCHAR(4) NULL,
    perm_location VARCHAR(800) NULL,
    perm_status VARCHAR(40) NULL,
    ctor_seq_nbr NUMERIC(15) NULL,
    cloc_seq_nbr NUMERIC(15) NULL,
    perm_fst_seq_nbr NUMERIC(15) NULL,
    perm_bid_amount NUMERIC(10, 2) NULL,
    perm_total_cost NUMERIC(10, 2) NULL,
    perm_legal_description VARCHAR(400) NULL,
    perm_gross_area NUMERIC(15, 7) NULL,
    perm_high_lvl_pln VARCHAR(120) NULL,
    perm_lcn_hvst_auth VARCHAR(120) NULL,
    perm_lcn_reg CHAR NULL,
    modifiedby VARCHAR(120) NULL,
    modifiedon TIMESTAMP NULL,
    modifiedusing VARCHAR(120) NULL,
    createdby VARCHAR(120) NULL,
    createdon TIMESTAMP NULL,
    createdusing VARCHAR(120) NULL,
    PRIMARY KEY (perm_seq_nbr)
);

ALTER TABLE lrm_replication.cut_permit OWNER TO bcts_etl_user;
