CREATE TABLE lrm_replication.division (
    divi_div_nbr NUMERIC(2) NOT NULL,
    divi_country_code VARCHAR(40) NOT NULL,
    divi_prov_state_code VARCHAR(40) NOT NULL,
    divi_division_name VARCHAR(50) NOT NULL,
    divi_startup_date TIMESTAMP NULL,
    divi_end_date TIMESTAMP NULL,
    divi_short_code VARCHAR(15) NULL,
    divi_line1_addr VARCHAR(120) NULL,
    divi_line2_addr VARCHAR(120) NULL,
    divi_line3_addr VARCHAR(120) NULL,
    divi_city_name VARCHAR(200) NULL,
    divi_postal_code VARCHAR(40) NULL,
    divi_intl_routing_code VARCHAR(60) NULL,
    divi_phone_nbr VARCHAR(40) NULL,
    divi_fax_nbr VARCHAR(40) NULL,
    divi_stmpg_acctcd VARCHAR(200) NULL,
    divi_stmpg_offset_acctcd VARCHAR(200) NULL,
    divi_walker_entity_acctcd VARCHAR(60) NULL,
    divi_gst_pay_acctcd VARCHAR(200) NULL,
    divi_gst_recovery_acctd VARCHAR(200) NULL,
    divi_operation_location_ind VARCHAR(4) NULL,
    divi_client_location_code VARCHAR(40) NULL,
    divi_abbreviation_code VARCHAR(16) NULL,
    modifiedby VARCHAR(120) NULL,
    modifiedon TIMESTAMP NULL,
    modifiedusing VARCHAR(120) NULL,
    createdby VARCHAR(120) NULL,
    createdon TIMESTAMP NULL,
    createdusing VARCHAR(120) NULL,
    PRIMARY KEY (divi_div_nbr)
);

