CREATE TABLE lrm_replication.management_unit (
    manu_seq_nbr NUMERIC(15) NOT NULL,
    divi_div_nbr NUMERIC(2) NOT NULL,
    manu_id VARCHAR(60) NOT NULL,
    manu_name VARCHAR(200) NULL,
    manu_comment VARCHAR(4000) NULL,
    manu_type_id VARCHAR(40) NULL,
    manu_operating_zone VARCHAR(40) NULL,
    manu_mgr_seq_nbr NUMERIC(15) NULL,
    manu_fst_seq_nbr NUMERIC(15) NULL,
    manu_digitize_ind VARCHAR(20) NULL,
    manu_area NUMERIC(11, 6) NULL,
    manu_net_area NUMERIC(11, 6) NULL,
    modifiedby VARCHAR(120) NULL,
    modifiedon TIMESTAMP NULL,
    modifiedusing VARCHAR(120) NULL,
    createdby VARCHAR(120) NULL,
    createdon TIMESTAMP NULL,
    createdusing VARCHAR(120) NULL,
    nat_res_area VARCHAR(1) NULL,
    nat_res_region VARCHAR(2) NULL,
    manu_aac_effect_date TIMESTAMP NULL,
    manu_aac NUMERIC(10, 2) NULL,
    non_bcts_aac_ind NUMERIC(1) NULL,
    PRIMARY KEY (manu_seq_nbr)
);
