apiVersion: v1
kind: Secret
metadata:
  name: lrm-ods-database
type: Opaque
stringData:
  ODS_USERNAME: bcts_etl_user
  ODS_PASSWORD: <place_holder>
  ODS_HOST: 172.28.0.10
  ODS_PORT: '5432'
  ODS_DATABASE: ods
  MSTR_SCHEMA: ods_data_management
  APP_NAME: lrm
  CONCUR_TASKS: '50'


 