CREATE TABLE results_replication.rslt_opening_polygon (
    opening_id NUMERIC(10),
    mapsheet_grid VARCHAR(3),
    mapsheet_letter VARCHAR(1),
    mapsheet_square VARCHAR(3),
    mapsheet VARCHAR(7),
    opening_number VARCHAR(4),
    map_label VARCHAR(12),
    opening_category_code VARCHAR(7),
    opening_status_code VARCHAR(3),
    opening_location_name VARCHAR(30),
    district_admin_zone VARCHAR(2),
    licensee_opening_id VARCHAR(30),
    max_allow_permnt_access_pct NUMERIC(3, 1),
    approve_date TIMESTAMP,
    tsb_number_code VARCHAR(3),
    amendment_ind VARCHAR(1),
    prev_tree_species1_code VARCHAR(8),
    prev_tree_species2_code VARCHAR(8),
    prev_stocking_status_code VARCHAR(3),
    prev_age_class_code VARCHAR(1),
    prev_height_class_code VARCHAR(1),
    prev_site_index NUMERIC(5),
    prev_site_index_source_code VARCHAR(1),
    results_submission_id NUMERIC(10),
    region_code VARCHAR(6),
    region_name VARCHAR(100),
    district_code VARCHAR(6),
    district_name VARCHAR(100),
    bcts_code VARCHAR(6),
    bcts_name VARCHAR(100),
    geo_region_code VARCHAR(6),
    geo_district_code VARCHAR(6),
    geo_district_name VARCHAR(100),
    opening_gross_area NUMERIC(11, 4),
    forest_file_id VARCHAR(10),
    cutting_permit_id VARCHAR(3),
    timber_mark VARCHAR(10),
    cut_block_id VARCHAR(10),
    mgmt_unit_id VARCHAR(4),
    mgmt_unit_type_code VARCHAR(1),
    mgmt_unit_description VARCHAR(100),
    file_type_code VARCHAR(3),
    disturbance_start_date TIMESTAMP,
    disturbance_end_date TIMESTAMP,
    client_name VARCHAR(60),
    client_number VARCHAR(8),
    client_location_code VARCHAR(2),
    generalized_bgc_zone_code VARCHAR(4),
    generalized_bgc_subzone_code VARCHAR(3),
    generalized_bgc_variant VARCHAR(1),
    generalized_bgc_phase VARCHAR(1),
    generalized_bec_site_series VARCHAR(4),
    generalized_bec_site_type VARCHAR(3),
    generalized_bec_seral VARCHAR(4),
    denudation_1_disturbance_code VARCHAR(3),
    denudation_1_silv_system_code VARCHAR(5),
    denudation_1_silv_variant_code VARCHAR(3),
    denudation_1_cut_phase_code VARCHAR(5),
    denudation_1_completion_date TIMESTAMP,
    denudation_2_disturbance_code VARCHAR(3),
    denudation_2_silv_system_code VARCHAR(5),
    denudation_2_silv_variant_code VARCHAR(3),
    denudation_2_cut_phase_code VARCHAR(5),
    denudation_2_completion_date TIMESTAMP,
    denudation_count NUMERIC,
    site_prep_1_technique_code VARCHAR(2),
    site_prep_1_treatment_area NUMERIC,
    site_prep_1_completion_date TIMESTAMP,
    site_prep_2_technique_code VARCHAR(2),
    site_prep_2_treatment_area NUMERIC,
    site_prep_2_completion_date TIMESTAMP,
    site_prep_count NUMERIC,
    planting_1_technique_code VARCHAR(2),
    planting_1_treatment_area NUMERIC,
    planting_1_completion_date TIMESTAMP,
    planting_2_technique_code VARCHAR(2),
    planting_2_treatment_area NUMERIC,
    planting_2_completion_date TIMESTAMP,
    planting_count NUMERIC,
    brushing_technique_code VARCHAR(2),
    brushing_treatment_area NUMERIC,
    brushing_completion_date TIMESTAMP,
    brushing_count NUMERIC,
    spacing_treatment_area NUMERIC,
    spacing_completion_date TIMESTAMP,
    spacing_count NUMERIC,
    fertilization_treatment_area NUMERIC,
    fertilization_completion_date TIMESTAMP,
    fertilization_count NUMERIC,
    pruning_treatment_area NUMERIC,
    pruning_completion_date TIMESTAMP,
    pruning_count NUMERIC,
    geometry_exist_ind VARCHAR(1),
    geometry TEXT,
    feature_area NUMERIC(11, 4),
    feature_perimeter NUMERIC(11, 4),
    feature_class_skey NUMERIC(10),
    capture_method_code VARCHAR(30),
    data_source_code VARCHAR(10),
    observation_date TIMESTAMP,
    data_quality_comment VARCHAR(255),
    submitted_by_userid VARCHAR(30),
    submitted_date TIMESTAMP,
    slope NUMERIC(4, 1),
    aspect NUMERIC(4, 1),
    maximum_elevation NUMERIC(6, 1),
    minimum_elevation NUMERIC(6, 1),
    average_elevation NUMERIC(6, 1),
    opening_sea_calc_result_code VARCHAR(10),
    opening_sea_confidence_code VARCHAR(10),
    opening_who_created VARCHAR(30),
    opening_when_created TIMESTAMP,
    opening_who_updated VARCHAR(30),
    opening_when_updated TIMESTAMP,
    objectid NUMERIC(10),
    change_timestamp1 TIMESTAMP,
    change_timestamp2 TIMESTAMP,
    change_timestamp3 TIMESTAMP,
    change_timestamp4 TIMESTAMP,
    change_timestamp5 TIMESTAMP,
    change_timestamp6 TIMESTAMP,
    change_timestamp7 TIMESTAMP,
    change_timestamp8 TIMESTAMP
);

CREATE TABLE results_replication.stocking_milestone (
    stocking_standard_unit_id NUMERIC(10),
    silv_milestone_type_code VARCHAR(3),
    results_submission_id NUMERIC(10),
    declared_date TIMESTAMP,
    declared_userid VARCHAR(30),
    declare_ind VARCHAR(1),
    declaration_submitted_date TIMESTAMP,
    early_offset_years NUMERIC(2),
    late_offset_years NUMERIC(2),
    due_early_date TIMESTAMP,
    due_late_date TIMESTAMP,
    entry_userid VARCHAR(30),
    entry_timestamp TIMESTAMP,
    update_userid VARCHAR(30),
    update_timestamp TIMESTAMP,
    revision_count NUMERIC(5),
    extent_feasible_declared_ind VARCHAR(1)
);

CREATE TABLE results_replication.stocking_standard_unit (
    stocking_standard_unit_id NUMERIC(10),
    opening_id NUMERIC(10),
    standards_unit_id VARCHAR(4),
    standards_regime_id NUMERIC(10),
    net_area NUMERIC(7, 1),
    max_allow_soil_disturbance_pct NUMERIC(3, 1),
    variance_ind VARCHAR(1),
    entry_userid VARCHAR(30),
    entry_timestamp TIMESTAMP,
    update_userid VARCHAR(30),
    update_timestamp TIMESTAMP,
    revision_count NUMERIC(5)
);

