# These secrets are used in the LOCAL evelopment environment. For the DAP environments, these secrets should be created in Openshift.
apiVersion: v1
kind: Secret
metadata:
  name: lrm-ods-database
type: Opaque
stringData:
  ODS_USERNAME: ods_proxy_user_lrm
  ODS_PASSWORD: ods_proxy_user_lrm
  ODS_HOST: 172.28.0.10
  ODS_PORT: '5432'
  ODS_DATABASE: ods
  MSTR_SCHEMA: ods_data_management
  APP_NAME: lrm
  CONCUR_TASKS: '50'


 