CREATE TABLE fta_replication.AAC_FILE_TYPE_CODE (
	AAC_FILE_TYPE_CODE VARCHAR(3) NOT NULL,
	DESCRIPTION VARCHAR(120) NOT NULL,
	EFFECTIVE_DATE TIMESTAMP(0) NOT NULL,
	EXPIRY_DATE TIMESTAMP(0) NOT NULL,
	UPDATE_TIMESTAMP TIMESTAMP(0) NOT NULL,
	CONSTRAINT AACFTC_PK PRIMARY KEY (AAC_FILE_TYPE_CODE)
	
);