CREATE TABLE fta_replication.ALLOWABLE_AREA_TYPE_CODE (
	ALLOWABLE_AREA_TYPE_CODE VARCHAR(3) NOT NULL,
	DESCRIPTION VARCHAR(120) NOT NULL,
	EFFECTIVE_DATE TIMESTAMP(0) NOT NULL,
	EXPIRY_DATE TIMESTAMP(0) NOT NULL,
	UPDATE_TIMESTAMP TIMESTAMP(0) NOT NULL,
	CONSTRAINT AWATC_PK PRIMARY KEY (ALLOWABLE_AREA_TYPE_CODE)
);