CREATE TABLE fta_replication.client_location (
	client_number VARCHAR(8) NOT NULL,
	client_locn_code VARCHAR(2) NOT NULL,
	client_locn_name VARCHAR(40),
	hdbs_company_code VARCHAR(5),
	address_1 VARCHAR(40) NOT NULL,
	address_2 VARCHAR(40),
	address_3 VARCHAR(40),
	city VARCHAR(30) NOT NULL,
	province VARCHAR(50),
	postal_code VARCHAR(10),
	country VARCHAR(50) NOT NULL,
	business_phone VARCHAR(10),
	home_phone VARCHAR(10),
	cell_phone VARCHAR(10),
	fax_number VARCHAR(10),
	email_address VARCHAR(128),
	locn_expired_ind VARCHAR(1) NOT NULL,
	returned_mail_date TIMESTAMP(0),
	trust_location_ind VARCHAR(1) NOT NULL,
	cli_locn_comment VARCHAR(4000),
	update_timestamp TIMESTAMP(0) NOT NULL,
	update_userid VARCHAR(30) NOT NULL,
	update_org_unit bigint NOT NULL,
	add_timestamp TIMESTAMP(0) NOT NULL,
	add_userid VARCHAR(30) NOT NULL,
	add_org_unit bigint NOT NULL,
	revision_count INT NOT NULL
);
