CREATE TABLE fta_replication.forest_client (
	client_number VARCHAR(8) NOT NULL,
	client_name VARCHAR(60) NOT NULL,
	legal_first_name VARCHAR(30),
	legal_middle_name VARCHAR(30),
	client_status_code VARCHAR(3) NOT NULL,
	client_type_code VARCHAR(1) NOT NULL,
	birthdate TIMESTAMP(0),
	client_id_type_code VARCHAR(4),
	client_identification VARCHAR(40),
	registry_company_type_code VARCHAR(4),
	corp_regn_nmbr VARCHAR(9),
	client_acronym VARCHAR(8),
	wcb_firm_number VARCHAR(6),
	ocg_supplier_nmbr VARCHAR(10),
	client_comment VARCHAR(4000),
	add_timestamp TIMESTAMP(0) NOT NULL,
	add_userid VARCHAR(30) NOT NULL,
	add_org_unit bigint NOT NULL,
	update_timestamp TIMESTAMP(0) NOT NULL,
	update_userid VARCHAR(30) NOT NULL,
	update_org_unit bigint NOT NULL,
	revision_count INT NOT NULL
);
