CREATE TABLE fta_replication.tenure_application (
	tenure_app_id bigint NOT NULL,
	tenure_appname VARCHAR(250) NOT NULL,
	submission_id bigint NOT NULL,
	forest_file_id VARCHAR(10),
	client_number VARCHAR(8) NOT NULL,
	client_locn_code VARCHAR(2) NOT NULL,
	tenure_application_type_code VARCHAR(3) NOT NULL,
	cascade_split_code VARCHAR(1),
	tenure_application_state_code VARCHAR(3) NOT NULL,
	tenure_app_purp_code VARCHAR(3) NOT NULL,
	adjudication_ind VARCHAR(1) DEFAULT 'n' NOT NULL,
	adjudicated_by VARCHAR(30),
	adjudication_date TIMESTAMP(0),
	adjudication_requested_ind VARCHAR(1) DEFAULT 'n' NOT NULL,
	current_assigned_to VARCHAR(4) NOT NULL,
	image_created_ind VARCHAR(1) DEFAULT 'n' NOT NULL,
	map_report_created_ind VARCHAR(1) DEFAULT 'n' NOT NULL,
	description VARCHAR(255),
	min_x bigint NOT NULL,
	min_y bigint NOT NULL,
	max_x bigint NOT NULL,
	max_y bigint NOT NULL,
	management_unit_number VARCHAR(10),
	management_unit_block VARCHAR(4),
	management_unit_sub_block VARCHAR(3),
	completion_date TIMESTAMP(0),
	finalized_by VARCHAR(30),
	submission_date TIMESTAMP(0) NOT NULL,
	image_error SMALLINT DEFAULT 0 NOT NULL,
	map_report_error SMALLINT DEFAULT 0 NOT NULL,
	spatial_data_error SMALLINT DEFAULT 0 NOT NULL,
	spatial_ind VARCHAR(1) DEFAULT 'n' NOT NULL,
	file_created_ind VARCHAR(1) DEFAULT 'n' NOT NULL,
	image_height SMALLINT,
	image_width SMALLINT,
	meters_per_pixel DECIMAL(10, 3),
	image_scale bigint,
	adjudication_comment VARCHAR(2000),
	cutting_permit_id VARCHAR(3),
	image_map_size_code VARCHAR(1),
	org_unit_no bigint NOT NULL,
	geo_org_unit_no bigint,
	image_mime_type_code VARCHAR(3),
	image_orientation_code VARCHAR(1),
	image_create_in_progress_ind VARCHAR(1) DEFAULT 'n' NOT NULL,
	image_create_requested_by VARCHAR(30),
	image_create_requested_date TIMESTAMP(0),
	overlay_geo_district_code VARCHAR(6),
	bcgs_mapsheet_no VARCHAR(32),
	tsa_number VARCHAR(2),
	land_district VARCHAR(50),
	pulpwood_agreement VARCHAR(20),
	utm_zone INT,
	revision_count INT NOT NULL,
	entry_userid VARCHAR(30) NOT NULL,
	entry_timestamp TIMESTAMP(0) NOT NULL,
	update_userid VARCHAR(30) NOT NULL,
	update_timestamp TIMESTAMP(0) NOT NULL,
	tenure_app_guid bytea NOT NULL,
	application_decision_message VARCHAR(1000),
	clearance_status_request_uri VARCHAR(2000),
	dependent_submission_reference VARCHAR(100),
	tenure_amendment_id bigint,
	business_amendment_id bigint,
	decision_date TIMESTAMP(0),
	issuance_date TIMESTAMP(0)
);

COMMENT ON column fta_replication.tenure_application.tenure_app_guid IS 'global unique identifier. created as part of the fta 5 changes.';

COMMENT ON column fta_replication.tenure_application.application_decision_message IS 'a free format text explaining the application processing results in detail.';

COMMENT ON column fta_replication.tenure_application.clearance_status_request_uri IS 'a universal reference identifier to the record''s status request entry in the status and clearance system.';

COMMENT ON column fta_replication.tenure_application.dependent_submission_reference IS 'a submission can have dependency on other submissions (those that already submitted or will be submitted in feature). the value would help the technical staff who working on resolving the overlap issues to get more info about the application being handled. there is another entity which provide the dependencies at detail level (feature) for the same purpose which is a child entity of the road application map feature.';

COMMENT ON column fta_replication.tenure_application.tenure_amendment_id IS 'contains the number of approved amendments done on a specific tenure. although the number can be calculated, it needs to be saved and persistent because there can be scenario in which two applications can be submitted against one tenure. if the one that was submitted later gets approved first the assigned amendment id won''t be correct. it needs to wait until the status of the second application becomes known. if first application also approved the next amendment id should be assigned to the it and the one that was approved before it going to have an amendment id equal to the first one plus one. the amendment id is and update-able column and will be updated if needed.';

COMMENT ON column fta_replication.tenure_application.business_amendment_id IS 'an integer representing the amendment id a licensee referencing with regards to a section.  fta 5 increments tenure amendment id by one when received a new application for an fta 5 tenure. there are cases that application get rejected or failed and re-submitted application again results in incrementing the tenure amendment id by 1. so, the amendment id referenced by the licensees and fta 5 staff get out of synch. this data item would help the licensees to reference their specific amendment id that they will use when communicating with the fta 5 staff.';
