CREATE TABLE fta_replication.tenure_application_map_feature (
	map_feature_id bigint NOT NULL,
	tenure_app_id bigint NOT NULL,
	forest_file_id VARCHAR(10),
	permit_block_id VARCHAR(4),
	cutting_permit_id VARCHAR(3),
	cut_block_id VARCHAR(10),
	road_section_id VARCHAR(30),
	amendment_id VARCHAR(5),
	fsr_dedication_plan_id VARCHAR(30),
	fsr_gravel_pit_no SMALLINT,
	chart_area_id VARCHAR(3),
	map_block_id VARCHAR(10),
	prov_forest_conflict_code VARCHAR(3),
	tenure_app_purp_code VARCHAR(3) NOT NULL,
	min_x bigint NOT NULL,
	max_x bigint NOT NULL,
	min_y bigint NOT NULL,
	max_y bigint NOT NULL,
	bcgs_map_sheet_reference VARCHAR(15),
	refer_to_file_number_desc VARCHAR(255),
	point_of_commencement VARCHAR(2000),
	image_height SMALLINT,
	image_width SMALLINT,
	meters_per_pixel DECIMAL(10, 3),
	object_area DECIMAL(15, 4),
	chart_volume DECIMAL(11, 4),
	image_scale bigint,
	object_length DECIMAL(15, 4),
	reference_name VARCHAR(50),
	feature_type_code VARCHAR(3),
	owned_by_file VARCHAR(10),
	owned_by_cp VARCHAR(3),
	managed_by_file VARCHAR(10),
	managed_by_cp VARCHAR(3),
	observation_date TIMESTAMP(0),
	data_source_code VARCHAR(10),
	data_quality_comment VARCHAR(255),
	capture_method_code VARCHAR(30),
	feature_class_skey bigint,
	planned_net_block_area DECIMAL(11, 4),
	image_mime_type_code VARCHAR(3),
	image_map_size_code VARCHAR(1),
	image_orientation_code VARCHAR(1),
	overlay_geo_district_code VARCHAR(6),
	bcgs_mapsheet_no VARCHAR(32),
	tsa_number VARCHAR(2),
	land_district VARCHAR(50),
	pulpwood_agreement VARCHAR(20),
	utm_zone INT,
	revision_count INT NOT NULL,
	update_userid VARCHAR(30) NOT NULL,
	update_timestamp TIMESTAMP(0) NOT NULL,
	entry_userid VARCHAR(30) NOT NULL,
	entry_timestamp TIMESTAMP(0) NOT NULL,
	map_feature_guid bytea NOT NULL,
	feature_record_guid bytea,
	business_feature_identifier VARCHAR(100)
);

COMMENT ON column fta_replication.tenure_application_map_feature.map_feature_guid IS 'a global unique identifier used to globally identify a tenure application feature record. it''s use to exchange record information with external applications and services ';

COMMENT ON column fta_replication.tenure_application_map_feature.feature_record_guid IS 'global unique identifier of a specific feature. this value is generic identifier of the feature (for example, a cut block) which is used to communicate with external application such as status & clearance service component tool.';

COMMENT ON column fta_replication.tenure_application_map_feature.business_feature_identifier IS 'contains concatenation of the key business attributes. the contents will be passed to the status and clearance.';
