DROP TABLE IF EXISTS lrm_replication.su_type;
CREATE TABLE lrm_replication.su_type (
    suty_type_id VARCHAR(40),
    suty_type_desc VARCHAR(160),
    suty_sort_order NUMERIC,
    suty_key_ind VARCHAR(20),
    suty_default_crown_closure NUMERIC(7, 4),
    modifiedby VARCHAR(120),
    modifiedon TIMESTAMP,
    modifiedusing VARCHAR(120),
    createdby VARCHAR(120),
    createdon TIMESTAMP,
    createdusing VARCHAR(120)
);

CREATE OR REPLACE VIEW bcts_staging.forestview_su_type AS
SELECT * FROM lrm_replication.su_type;

CREATE TABLE lrm_replication.silviculture_stratum (
    sist_seq_nbr NUMERIC(15),
    cutb_seq_nbr NUMERIC(15),
    sist_stratum_name VARCHAR(50),
    stst_stocking_status_id VARCHAR(40),
    sist_digitised_ind VARCHAR(1),
    sist_ha_area NUMERIC(11, 6),
    sist_green_up_date TIMESTAMP,
    sist_green_up_ind VARCHAR(4),
    sist_free_grow_date TIMESTAMP,
    sist_free_grow_ind VARCHAR(4),
    sist_regen_delay_met_date TIMESTAMP,
    sist_regen_delay_met_ind VARCHAR(4),
    sila_seq_nbr NUMERIC(15),
    sist_post_harvest_date TIMESTAMP,
    sist_post_harvest_ind VARCHAR(4),
    sist_nonmap_parent NUMERIC(15),
    sist_establishment_year TIMESTAMP,
    sist_crop_stems_per_ha NUMERIC(5),
    sist_total_stems_per_ha NUMERIC(5),
    sist_site_index NUMERIC(2),
    sist_pct_distribution NUMERIC(3),
    sist_pct_productive NUMERIC(3),
    sist_prefix VARCHAR(120),
    sist_class VARCHAR(120),
    modifiedby VARCHAR(120),
    modifiedon TIMESTAMP,
    modifiedusing VARCHAR(120),
    createdby VARCHAR(120),
    createdon TIMESTAMP,
    createdusing VARCHAR(120)
);

CREATE OR REPLACE VIEW bcts_staging.forestview_silviculture_stratum AS
SELECT * FROM lrm_replication.silviculture_stratum;

CREATE TABLE lrm_replication.silviculture_stocking_status (
    sist_seq_nbr NUMERIC(15),
    slay_layer VARCHAR(10),
    srnk_rank VARCHAR(10),
    sttp_stocking_type_id VARCHAR(10),
    ssts_survey_source VARCHAR(60),
    ssts_survey_date TIMESTAMP,
    ssts_stock_age NUMERIC,
    ssts_stock_age_plant NUMERIC,
    ssts_stock_height NUMERIC(10, 4),
    ssts_crown_closure NUMERIC(7, 4),
    ssts_reference_year NUMERIC(4),
    sicl_site_class VARCHAR(10),
    ssts_site_index NUMERIC(10),
    ssts_density NUMERIC(10, 1),
    ssts_well_spaced_density NUMERIC(10, 1),
    ssts_free_growing_density NUMERIC(10, 1),
    srty_reserve_type VARCHAR(10),
    ssts_basal_area NUMERIC(7, 2),
    ssts_cm_top_height NUMERIC(10, 4),
    ssts_cm_leader NUMERIC(10, 4),
    ssts_vigour_pct_good NUMERIC(7, 4),
    ssts_vigour_pct_medium NUMERIC(7, 4),
    ssts_vigour_pct_poor NUMERIC(7, 4),
    ssts_comments VARCHAR(4000),
    ssts_total_coniferous NUMERIC(10),
    ssts_plantable_spots NUMERIC(10),
    ssts_prepable_slash_spots NUMERIC(10),
    ssts_prepable_brush_spots NUMERIC(10),
    ssts_prepable_duff_spots NUMERIC(10),
    ssts_non_productive_spots NUMERIC(10),
    ssts_formc_printed_ind VARCHAR(4),
    ssts_formc_date TIMESTAMP,
    stst_stocking_status_id VARCHAR(10),
    ssts_root_collar_diameter NUMERIC(10),
    sssc_source_code VARCHAR(10),
    ssts_free_grow_density_pref NUMERIC(10, 1),
    ssts_well_spaced_density_pref NUMERIC(10, 1),
    ssts_free_grow_lcl_density NUMERIC(10, 1),
    ssts_well_spaced_lcl_density NUMERIC(10, 1),
    ssts_countable_conifers NUMERIC(10),
    ssts_reentry_year NUMERIC(4),
    ssts_cvr_pattern VARCHAR(10),
    ssts_res_objective VARCHAR(10),
    ssts_total_well_spaced NUMERIC(10, 1),
    ssts_germinant_per_ha NUMERIC(10, 1),
    ssts_greened_up_tree_per_ha NUMERIC(10, 1),
    ssts_total_trees_pa_fg NUMERIC(10),
    ssts_total_trees_p_fg NUMERIC(10),
    ssts_total_trees_wpa_fg NUMERIC(10),
    ssts_total_trees_wp_fg NUMERIC(10),
    ssts_decid_p_fg NUMERIC(10),
    ssts_tpi_pa_fg NUMERIC(10, 1),
    ssts_ppi_pa_fg NUMERIC(10, 1),
    ssts_ppi_low_conf_limit_fg NUMERIC(10, 1),
    ssts_ppi_sampling_error_fg NUMERIC(10, 1),
    ssts_total_trees_pa_regen NUMERIC(10),
    ssts_total_trees_p_regen NUMERIC(10),
    ssts_total_trees_wpa_regen NUMERIC(10),
    ssts_total_trees_wp_regen NUMERIC(10),
    ssts_decid_p_regen NUMERIC(10),
    ssts_tpi_pa_regen NUMERIC(10, 1),
    ssts_ppi_pa_regen NUMERIC(10, 1),
    ssts_ppi_low_conf_limit_regen NUMERIC(10, 1),
    ssts_ppi_sampling_error_regen NUMERIC(10, 1),
    modifiedby VARCHAR(120),
    modifiedon TIMESTAMP,
    modifiedusing VARCHAR(120),
    createdby VARCHAR(120),
    createdon TIMESTAMP,
    createdusing VARCHAR(120)
);

CREATE OR REPLACE VIEW bcts_staging.forestview_silviculture_stocking_status AS
SELECT * FROM lrm_replication.silviculture_stocking_status;


CREATE TABLE lrm_replication.biogeoclimatic_zone (
    bioz_zone_id VARCHAR(40),
    bioz_zone_name VARCHAR(120),
    bioz_active_ind VARCHAR(4),
    modifiedby VARCHAR(120),
    modifiedon TIMESTAMP,
    modifiedusing VARCHAR(120),
    createdby VARCHAR(120),
    createdon TIMESTAMP,
    createdusing VARCHAR(120)
);

CREATE OR REPLACE VIEW bcts_staging.forestview_biogeoclimatic_zone AS
SELECT * FROM lrm_replication.biogeoclimatic_zone;

CREATE TABLE lrm_replication.biogeoclimatic_subzone (
    bioz_zone_id VARCHAR(40),
    bios_subzone_id VARCHAR(40),
    bios_subzone_name VARCHAR(200),
    bios_active_ind VARCHAR(4),
    modifiedby VARCHAR(120),
    modifiedon TIMESTAMP,
    modifiedusing VARCHAR(120),
    createdby VARCHAR(120),
    createdon TIMESTAMP,
    createdusing VARCHAR(120)
);
CREATE OR REPLACE VIEW bcts_staging.forestview_biogeoclimatic_subzone AS
SELECT * FROM lrm_replication.biogeoclimatic_subzone;

CREATE TABLE lrm_replication.biogeoclimatic_variant (
    bioz_zone_id VARCHAR(40),
    bios_subzone_id VARCHAR(40),
    biov_variant_id VARCHAR(40),
    biov_variant_name VARCHAR(200),
    biov_active_ind VARCHAR(4),
    modifiedby VARCHAR(120),
    modifiedon TIMESTAMP,
    modifiedusing VARCHAR(120),
    createdby VARCHAR(120),
    createdon TIMESTAMP,
    createdusing VARCHAR(120)
);

CREATE OR REPLACE VIEW bcts_staging.forestview_biogeoclimatic_variant AS
SELECT * FROM lrm_replication.biogeoclimatic_variant;

CREATE TABLE lrm_replication.silviculture_activity (
    sila_seq_nbr NUMERIC(15),
    cutb_seq_nbr NUMERIC(15),
    sica_seq_nbr NUMERIC(15),
    sila_status VARCHAR(30),
    sila_gross_ha_area NUMERIC(11, 6),
    sila_digitised_ind VARCHAR(4),
    sila_start_date TIMESTAMP,
    sila_completion_date TIMESTAMP,
    fund_funding_code VARCHAR(10),
    resp_responsibility_code VARCHAR(40),
    sila_contractor_id VARCHAR(200),
    sila_formb_printed VARCHAR(1),
    sila_formb_date TIMESTAMP,
    sisy_silvicultural_system_id VARCHAR(60),
    siva_variant_id VARCHAR(60),
    siph_cut_phase_id VARCHAR(60),
    sila_reserve_type VARCHAR(60),
    sila_disturbance_code VARCHAR(60),
    hame_method_id VARCHAR(40),
    sila_harvest_volume NUMERIC(15, 6),
    sila_cost_per_ha NUMERIC(16, 5),
    sila_machine_hours NUMERIC(7, 2),
    sila_plantable_spots NUMERIC(10, 1),
    sila_soil_disturbance NUMERIC(7, 4),
    sila_season VARCHAR(60),
    sila_percent_paid NUMERIC(7, 4),
    sila_brush_chemical VARCHAR(200),
    sila_brush_active NUMERIC(9, 6),
    sila_brush_target_species1 VARCHAR(60),
    sila_brush_target_species2 VARCHAR(60),
    sila_brush_deciduous NUMERIC(10),
    sila_brush_apply_rate NUMERIC(13, 4),
    sila_brush_pmp_pup_nbr VARCHAR(60),
    ctor_seq_nbr NUMERIC(15),
    sila_treatment_unit_id VARCHAR(40),
    stst_stocking_status_id VARCHAR(40),
    sila_total_stocking_pct NUMERIC(5, 2),
    sila_project_num VARCHAR(80),
    cloc_seq_nbr NUMERIC(15),
    sila_cost_per_ha_plan NUMERIC(16, 5),
    sila_treated_area NUMERIC(11, 6),
    pers_seq_nbr NUMERIC(15),
    oalt_object_id VARCHAR(8),
    objt_seq_nbr NUMERIC(15),
    hrun_seq_nbr NUMERIC(15),
    sila_start_date_planned TIMESTAMP,
    sila_completion_date_planned TIMESTAMP,
    sila_net_area NUMERIC(11, 6),
    surveyor_seq_nbr NUMERIC(15),
    recorder_seq_nbr NUMERIC(15),
    sila_activity_approval_status VARCHAR(40),
    sila_priority VARCHAR(120),
    sila_comments VARCHAR(4000),
    sila_cost_unit VARCHAR(40),
    sila_budgeted_ind VARCHAR(4),
    sila_prev_formb_date TIMESTAMP,
    sila_allocation_id VARCHAR(120),
    sila_harvest_area_finalized VARCHAR(4),
    sila_plan_lock_ind VARCHAR(4),
    sila_act_lock_ind VARCHAR(4),
    atu_id VARCHAR(200),
    sila_retreatment_ind VARCHAR(4),
    sila_sdd_submission VARCHAR(120),
    modifiedby VARCHAR(120),
    modifiedon TIMESTAMP,
    modifiedusing VARCHAR(120),
    createdby VARCHAR(120),
    createdon TIMESTAMP,
    createdusing VARCHAR(120),
    documentkey NUMERIC(9)
);
CREATE OR REPLACE VIEW bcts_staging.forestview_silviculture_activity AS
SELECT * FROM lrm_replication.silviculture_activity;

CREATE TABLE lrm_replication.planting_unit (
    plun_seq_nbr NUMERIC(15),
    sila_seq_nbr NUMERIC(15),
    plun_digitised_ind VARCHAR(1),
    plun_ha_area NUMERIC(11, 6),
    plun_quality_percent NUMERIC(7, 4),
    plun_planting_cost NUMERIC(15, 5),
    plun_planting_unit_id NUMERIC(3),
    plun_survival_pct NUMERIC(7, 4),
    plun_last_survival_check TIMESTAMP,
    plun_contract_min_spacing NUMERIC(7, 2),
    plun_contract_target_spacing NUMERIC(7, 2),
    plun_contract_max_spacing NUMERIC(7, 2),
    plun_planting_plan_cost NUMERIC(15, 5),
    plun_row NUMERIC(7, 2),
    plun_net_area NUMERIC(11, 6),
    plun_drill NUMERIC(6, 2),
    plun_min_stock_size VARCHAR(120),
    plun_max_stock_size VARCHAR(120),
    plun_plan_cost_per_unit NUMERIC(15, 5),
    plun_cost_per_unit NUMERIC(15, 5),
    plun_density NUMERIC(7, 2),
    plun_lock_ind VARCHAR(4),
    modifiedby VARCHAR(120),
    modifiedon TIMESTAMP,
    modifiedusing VARCHAR(120),
    createdby VARCHAR(120),
    createdon TIMESTAMP,
    createdusing VARCHAR(120),
    when_area_is_changed VARCHAR(120),
    plsp_editing_trees_or_pct VARCHAR(120),
    total_trees NUMERIC(12),
    plun_cost_per_tree NUMERIC(15, 5),
    plun_planned_cost_per_tree NUMERIC(15, 5),
    plun_cost_per_ha NUMERIC(15, 5),
    plun_planned_cost_per_ha NUMERIC(15, 5)
);

CREATE OR REPLACE VIEW bcts_staging.forestview_planting_unit AS
SELECT * FROM lrm_replication.planting_unit;

CREATE TABLE lrm_replication.brushing_target_species (
    btrs_seq_nbr NUMERIC(15),
    sila_seq_nbr NUMERIC(15),
    sisp_species_id VARCHAR(60),
    btrs_coverage_pct NUMERIC(3),
    btrs_height NUMERIC(10, 4),
    btrs_broadleaf_tree_diameter NUMERIC(13, 4),
    modifiedby VARCHAR(120),
    modifiedon TIMESTAMP,
    modifiedusing VARCHAR(120),
    createdby VARCHAR(120),
    createdon TIMESTAMP,
    createdusing VARCHAR(120)
);

CREATE OR REPLACE VIEW bcts_staging.forestview_brushing_target_species AS
SELECT * FROM lrm_replication.brushing_target_species;

CREATE TABLE lrm_replication.silv_activity_cost (
    sacc_seq_nbr NUMERIC(15),
    sila_seq_nbr NUMERIC(15),
    plun_seq_nbr NUMERIC(15),
    scac_seq_nbr NUMERIC(15),
    sacc_item_cost NUMERIC(13, 4),
    sacc_comment VARCHAR(4000),
    sacc_series VARCHAR(40),
    modifiedby VARCHAR(120),
    modifiedon TIMESTAMP,
    modifiedusing VARCHAR(120),
    createdby VARCHAR(120),
    createdon TIMESTAMP,
    createdusing VARCHAR(120)
);

CREATE OR REPLACE VIEW bcts_staging.forestview_silv_activity_cost AS
SELECT * FROM lrm_replication.silv_activity_cost;

CREATE TABLE lrm_replication.planting_species (
    plsp_seq_nbr NUMERIC(15),
    plun_seq_nbr NUMERIC(15),
    sisp_species_id VARCHAR(15),
    plsp_number_trees NUMERIC(10),
    sisl_seed_lot_number VARCHAR(200),
    sirk_request_key VARCHAR(60),
    plsp_seed_weight NUMERIC(12, 4),
    plsp_price_per_tree NUMERIC(13, 4),
    plsp_comment VARCHAR(4000),
    ssfm_seq_nbr NUMERIC(15),
    sinu_code VARCHAR(24),
    plsp_stock_type VARCHAR(40),
    plsp_lift_date TIMESTAMP,
    plsp_trees_outside_zone NUMERIC(7),
    plsp_yrs_orig_cntnr NUMERIC(5),
    plsp_yrs_transplanted NUMERIC(5),
    modifiedby VARCHAR(120),
    modifiedon TIMESTAMP,
    modifiedusing VARCHAR(120),
    createdby VARCHAR(120),
    createdon TIMESTAMP,
    createdusing VARCHAR(120),
    v_outside_transfer_limit VARCHAR(2),
    cbst_comments VARCHAR(500)
);

CREATE OR REPLACE VIEW bcts_staging.forestview_planting_species AS
SELECT * FROM lrm_replication.planting_species;

CREATE TABLE lrm_replication.silv_company_activity_cost (
    scac_seq_nbr NUMERIC(15),
    sica_seq_nbr NUMERIC(15),
    csti_cost_item_id VARCHAR(40),
    divi_div_nbr NUMERIC(2),
    scac_active_ind VARCHAR(4),
    scac_display_order NUMERIC(4),
    modifiedby VARCHAR(120),
    modifiedon TIMESTAMP,
    modifiedusing VARCHAR(120),
    createdby VARCHAR(120),
    createdon TIMESTAMP,
    createdusing VARCHAR(120)
);

CREATE OR REPLACE VIEW bcts_staging.forestview_silv_company_activity_cost AS
SELECT * FROM lrm_replication.silv_company_activity_cost;

CREATE TABLE lrm_replication.frst_cost_item (
    csti_cost_item_id VARCHAR(40),
    divi_div_nbr NUMERIC(2),
    csti_cost_item_description VARCHAR(200),
    csti_cost_item_active_ind VARCHAR(4),
    csti_cost_item_display_order NUMERIC(4),
    csti_cost_item_account_code VARCHAR(200),
    modifiedby VARCHAR(120),
    modifiedon TIMESTAMP,
    modifiedusing VARCHAR(120),
    createdby VARCHAR(120),
    createdon TIMESTAMP,
    createdusing VARCHAR(120)
);

CREATE OR REPLACE VIEW bcts_staging.forestview_frst_cost_item AS
SELECT * FROM lrm_replication.frst_cost_item;

CREATE TABLE lrm_replication.silviculture_company_activity (
    sica_seq_nbr NUMERIC(15),
    divi_div_nbr NUMERIC(2),
    siab_base_code VARCHAR(15),
    siat_technique_code VARCHAR(15),
    siam_method_code VARCHAR(15),
    sica_activity_name VARCHAR(50),
    siao_objective_code VARCHAR(60),
    siao_objective_code2 VARCHAR(60),
    siao_objective_code3 VARCHAR(60),
    sica_default_ind VARCHAR(4),
    sica_sort_order NUMERIC(10),
    sica_key_ind VARCHAR(3),
    sica_status_ind VARCHAR(4),
    sica_date_relative VARCHAR(20),
    sica_date_rel_start_end VARCHAR(4),
    sica_cost_per_ha NUMERIC(10, 5),
    sica_default_area_pct NUMERIC(7, 4),
    sica_current_status_ind VARCHAR(4),
    sica_liability_pct NUMERIC(7, 4),
    sica_active_ind VARCHAR(1),
    sica_pre_harvest_ind VARCHAR(4),
    sica_silv_regime_comments_ind VARCHAR(4),
    sica_system_code VARCHAR(40),
    sica_layer_class VARCHAR(72),
    sica_window VARCHAR(200),
    sica_rotation_ind VARCHAR(4),
    sica_inv_type_id VARCHAR(40),
    sica_establ_method_ind VARCHAR(4),
    sica_group VARCHAR(120),
    sica_comment VARCHAR(4000),
    sica_cost_type VARCHAR(120),
    modifiedby VARCHAR(120),
    modifiedon TIMESTAMP,
    modifiedusing VARCHAR(120),
    createdby VARCHAR(120),
    createdon TIMESTAMP,
    createdusing VARCHAR(120),
    update_planned_act_flag VARCHAR(3),
    sica_spatial_ind NUMERIC(1)
);

CREATE OR REPLACE VIEW bcts_staging.forestview_silviculture_company_activity AS
SELECT * FROM lrm_replication.silviculture_company_activity;

CREATE TABLE lrm_replication.detailed_site_assessment (
    sila_seq_nbr NUMERIC(15),
    dsas_stratum_name VARCHAR(200),
    potr_purpose_of_treatment VARCHAR(40),
    dsas_water_bodies VARCHAR(4),
    dsas_fish_habitat VARCHAR(4),
    dsas_wildlife_habitat VARCHAR(4),
    dsas_community_watershed VARCHAR(4),
    dsas_buffer_size NUMERIC(3),
    dsas_chemical VARCHAR(200),
    dsas_active NUMERIC(9, 6),
    dsas_apply_rate NUMERIC(13, 4),
    dsas_pmp_pup_nbr VARCHAR(60),
    dsas_referal_ind VARCHAR(4),
    dsas_referal VARCHAR(200),
    dsas_approval_ind VARCHAR(4),
    dsas_pfz_width NUMERIC(7, 2),
    pmpl_pmp_nbr VARCHAR(72),
    dsas_actual_brush_stems NUMERIC(7, 2),
    dsas_performance_quality_pct NUMERIC(6, 2),
    dsas_product_id VARCHAR(80),
    dsas_chemical_secondary VARCHAR(200),
    dsas_product_id_secondary VARCHAR(80),
    dsas_solution_volume_total NUMERIC(11, 2),
    dsas_solution_volume NUMERIC(11, 2),
    dsas_mix_load_location VARCHAR(600),
    modifiedby VARCHAR(120),
    modifiedon TIMESTAMP,
    modifiedusing VARCHAR(120),
    createdby VARCHAR(120),
    createdon TIMESTAMP,
    createdusing VARCHAR(120)
);

CREATE OR REPLACE VIEW bcts_staging.forestview_detailed_site_assessment AS
SELECT * FROM lrm_replication.detailed_site_assessment;

-- SOurce: DBQ01
CREATE TABLE lrm_replication.stocking_milestone (
    stocking_standard_unit_id NUMERIC(10),
    silv_milestone_type_code VARCHAR(3),
    results_submission_id NUMERIC(10),
    declared_date TIMESTAMP,
    declared_userid VARCHAR(30),
    declare_ind VARCHAR(1),
    declaration_submitted_date TIMESTAMP,
    early_offset_years NUMERIC(2),
    late_offset_years NUMERIC(2),
    due_early_date TIMESTAMP,
    due_late_date TIMESTAMP,
    entry_userid VARCHAR(30),
    entry_timestamp TIMESTAMP,
    update_userid VARCHAR(30),
    update_timestamp TIMESTAMP,
    revision_count NUMERIC(5),
    extent_feasible_declared_ind VARCHAR(1)
);
CREATE TABLE bcts_reporting.forestview_stocking_milestone AS SELECT * FROM lrm_replication.stocking_milestone;

CREATE TABLE lrm_replication.stocking_standard_unit (
    stocking_standard_unit_id NUMERIC(10),
    opening_id NUMERIC(10),
    standards_unit_id VARCHAR(4),
    standards_regime_id NUMERIC(10),
    net_area NUMERIC(7, 1),
    max_allow_soil_disturbance_pct NUMERIC(3, 1),
    variance_ind VARCHAR(1),
    entry_userid VARCHAR(30),
    entry_timestamp TIMESTAMP,
    update_userid VARCHAR(30),
    update_timestamp TIMESTAMP,
    revision_count NUMERIC(5)
);
CREATE TABLE bcts_reporting.forestview_stocking_standard_unit AS SELECT * FROM lrm_replication.stocking_standard_unit;
CREATE TABLE lrm_replication.rslt_opening_polygon (
    opening_id NUMERIC(10),
    mapsheet_grid VARCHAR(3),
    mapsheet_letter VARCHAR(1),
    mapsheet_square VARCHAR(3),
    mapsheet VARCHAR(7),
    opening_number VARCHAR(4),
    map_label VARCHAR(12),
    opening_category_code VARCHAR(7),
    opening_status_code VARCHAR(3),
    opening_location_name VARCHAR(30),
    district_admin_zone VARCHAR(2),
    licensee_opening_id VARCHAR(30),
    max_allow_permnt_access_pct NUMERIC(3, 1),
    approve_date TIMESTAMP,
    tsb_number_code VARCHAR(3),
    amendment_ind VARCHAR(1),
    prev_tree_species1_code VARCHAR(8),
    prev_tree_species2_code VARCHAR(8),
    prev_stocking_status_code VARCHAR(3),
    prev_age_class_code VARCHAR(1),
    prev_height_class_code VARCHAR(1),
    prev_site_index NUMERIC(5),
    prev_site_index_source_code VARCHAR(1),
    results_submission_id NUMERIC(10),
    region_code VARCHAR(6),
    region_name VARCHAR(100),
    district_code VARCHAR(6),
    district_name VARCHAR(100),
    bcts_code VARCHAR(6),
    bcts_name VARCHAR(100),
    geo_region_code VARCHAR(6),
    geo_district_code VARCHAR(6),
    geo_district_name VARCHAR(100),
    opening_gross_area NUMERIC(11, 4),
    forest_file_id VARCHAR(10),
    cutting_permit_id VARCHAR(3),
    timber_mark VARCHAR(10),
    cut_block_id VARCHAR(10),
    mgmt_unit_id VARCHAR(4),
    mgmt_unit_type_code VARCHAR(1),
    mgmt_unit_description VARCHAR(100),
    file_type_code VARCHAR(3),
    disturbance_start_date TIMESTAMP,
    disturbance_end_date TIMESTAMP,
    client_name VARCHAR(60),
    client_number VARCHAR(8),
    client_location_code VARCHAR(2),
    generalized_bgc_zone_code VARCHAR(4),
    generalized_bgc_subzone_code VARCHAR(3),
    generalized_bgc_variant VARCHAR(1),
    generalized_bgc_phase VARCHAR(1),
    generalized_bec_site_series VARCHAR(4),
    generalized_bec_site_type VARCHAR(3),
    generalized_bec_seral VARCHAR(4),
    denudation_1_disturbance_code VARCHAR(3),
    denudation_1_silv_system_code VARCHAR(5),
    denudation_1_silv_variant_code VARCHAR(3),
    denudation_1_cut_phase_code VARCHAR(5),
    denudation_1_completion_date TIMESTAMP,
    denudation_2_disturbance_code VARCHAR(3),
    denudation_2_silv_system_code VARCHAR(5),
    denudation_2_silv_variant_code VARCHAR(3),
    denudation_2_cut_phase_code VARCHAR(5),
    denudation_2_completion_date TIMESTAMP,
    denudation_count NUMERIC,
    site_prep_1_technique_code VARCHAR(2),
    site_prep_1_treatment_area NUMERIC,
    site_prep_1_completion_date TIMESTAMP,
    site_prep_2_technique_code VARCHAR(2),
    site_prep_2_treatment_area NUMERIC,
    site_prep_2_completion_date TIMESTAMP,
    site_prep_count NUMERIC,
    planting_1_technique_code VARCHAR(2),
    planting_1_treatment_area NUMERIC,
    planting_1_completion_date TIMESTAMP,
    planting_2_technique_code VARCHAR(2),
    planting_2_treatment_area NUMERIC,
    planting_2_completion_date TIMESTAMP,
    planting_count NUMERIC,
    brushing_technique_code VARCHAR(2),
    brushing_treatment_area NUMERIC,
    brushing_completion_date TIMESTAMP,
    brushing_count NUMERIC,
    spacing_treatment_area NUMERIC,
    spacing_completion_date TIMESTAMP,
    spacing_count NUMERIC,
    fertilization_treatment_area NUMERIC,
    fertilization_completion_date TIMESTAMP,
    fertilization_count NUMERIC,
    pruning_treatment_area NUMERIC,
    pruning_completion_date TIMESTAMP,
    pruning_count NUMERIC,
    geometry_exist_ind VARCHAR(1),
    geometry TEXT,
    feature_area NUMERIC(11, 4),
    feature_perimeter NUMERIC(11, 4),
    feature_class_skey NUMERIC(10),
    capture_method_code VARCHAR(30),
    data_source_code VARCHAR(10),
    observation_date TIMESTAMP,
    data_quality_comment VARCHAR(255),
    submitted_by_userid VARCHAR(30),
    submitted_date TIMESTAMP,
    slope NUMERIC(4, 1),
    aspect NUMERIC(4, 1),
    maximum_elevation NUMERIC(6, 1),
    minimum_elevation NUMERIC(6, 1),
    average_elevation NUMERIC(6, 1),
    opening_sea_calc_result_code VARCHAR(10),
    opening_sea_confidence_code VARCHAR(10),
    opening_who_created VARCHAR(30),
    opening_when_created TIMESTAMP,
    opening_who_updated VARCHAR(30),
    opening_when_updated TIMESTAMP,
    objectid NUMERIC(10),
    change_timestamp1 TIMESTAMP,
    change_timestamp2 TIMESTAMP,
    change_timestamp3 TIMESTAMP,
    change_timestamp4 TIMESTAMP,
    change_timestamp5 TIMESTAMP,
    change_timestamp6 TIMESTAMP,
    change_timestamp7 TIMESTAMP,
    change_timestamp8 TIMESTAMP
);
CREATE TABLE bcts_reporting.forestview_rslt_opening_polygon AS SELECT * FROM lrm_replication.rslt_opening_polygon;



