-- DROP TABLE IF EXISTS bcts_staging.silviliability_main_hist;

CREATE TABLE IF NOT EXISTS bcts_staging.silviliability_main_hist
(
    business_area_region_category text COLLATE pg_catalog."default",
    business_area_region text COLLATE pg_catalog."default",
    business_area text COLLATE pg_catalog."default",
    business_area_code character varying(16) COLLATE pg_catalog."default",
    field_team character varying(150) COLLATE pg_catalog."default",
    manu_id character varying(60) COLLATE pg_catalog."default",
    tenure character varying(40) COLLATE pg_catalog."default",
    licence character varying(15) COLLATE pg_catalog."default",
    hbs_first_billing timestamp without time zone,
    hbs_volume_billed numeric,
    block_id character varying(20) COLLATE pg_catalog."default",
    block_nbr character varying(15) COLLATE pg_catalog."default",
    ubi character varying(15) COLLATE pg_catalog."default",
    block_state character varying(20) COLLATE pg_catalog."default",
    fg_done timestamp without time zone,
    results_fg_declared timestamp without time zone,
    cutb_opening character varying(15) COLLATE pg_catalog."default",
    sp_exempt character varying(4) COLLATE pg_catalog."default",
    cruise_volume numeric(15,6),
    nar_area numeric,
    largest_eco_area numeric,
    count_bec_with_largest_eco_area bigint,
    bec text COLLATE pg_catalog."default",
    bio_zone text COLLATE pg_catalog."default",
    bio_subzone text COLLATE pg_catalog."default",
    bio_variant text COLLATE pg_catalog."default",
    hvs_status text COLLATE pg_catalog."default",
    hvs_date timestamp without time zone,
    hvs_fiscal numeric,
    hvc_status text COLLATE pg_catalog."default",
    hvc_date timestamp without time zone,
    hvc_fiscal numeric,
    treatment_unit character varying(40) COLLATE pg_catalog."default",
    block_funding character varying(15) COLLATE pg_catalog."default",
    activity_funding character varying(10) COLLATE pg_catalog."default",
    base character varying(15) COLLATE pg_catalog."default",
    technique character varying(15) COLLATE pg_catalog."default",
    method character varying(15) COLLATE pg_catalog."default",
    activity character varying(50) COLLATE pg_catalog."default",
    status character varying COLLATE pg_catalog."default",
    start_date timestamp without time zone,
    start_fiscal numeric,
    complete_date timestamp without time zone,
    complete_fiscal numeric,
    treatment_area numeric,
    sila_gross_area_char text COLLATE pg_catalog."default",
    cost_per_ha_plan numeric,
    cost_per_ha numeric,
    planned_total_cost numeric,
    cost_per_ha_plan_x_ha numeric,
    actual_total_cost numeric,
    cost_per_ha_x_ha numeric,
    planned_service_line character varying(200) COLLATE pg_catalog."default",
    planned_sl_description character varying(200) COLLATE pg_catalog."default",
    items_planned_total_cost numeric,
    actual_service_line character varying(200) COLLATE pg_catalog."default",
    actual_sl_description character varying(200) COLLATE pg_catalog."default",
    items_actual_total_cost numeric,
    planting_unit numeric(3,0),
    plun_digitised_ind character varying(1) COLLATE pg_catalog."default",
    plun_planned_total_cost numeric(15,5),
    plun_item_planned_total_cost numeric,
    plun_actual_total_cost numeric(15,5),
    plun_item_actual_total_cost numeric,
    plun_ha_area numeric(11,6),
    plun_net_area numeric(11,6),
    plun_density numeric(7,2),
    total_trees numeric(12,0),
    seedling_request text COLLATE pg_catalog."default",
    sica_key_ind character varying(3) COLLATE pg_catalog."default",
    plun_modifiedby character varying(120) COLLATE pg_catalog."default",
    plun_modifiedon timestamp without time zone,
    plun_modifiedusing character varying(120) COLLATE pg_catalog."default",
    modifiedby character varying(120) COLLATE pg_catalog."default",
    modifiedon timestamp without time zone,
    primary_record text COLLATE pg_catalog."default",
    need_planting text COLLATE pg_catalog."default",
    salvage_any_fire_year text COLLATE pg_catalog."default",
    salvage_fire_years text COLLATE pg_catalog."default",
    salvage_2021_fire text COLLATE pg_catalog."default",
    salvage_2022_fire text COLLATE pg_catalog."default",
    salvage_2023_fire text COLLATE pg_catalog."default",
    salvage_2024_fire text COLLATE pg_catalog."default",
    salvage_2025_fire text COLLATE pg_catalog."default",
    plun_seq_nbr numeric,
    sila_seq_nbr numeric(15,0),
    sica_seq_nbr numeric(15,0),
    cutb_seq_nbr bigint,
    licn_seq_nbr bigint,
    report_run_date DEFAULT CURRENT_DATE
)
