CREATE INDEX idx_v_block_cutb_seq_nbr ON LRM_REPLICATION.V_BLOCK (CUTB_SEQ_NBR);
CREATE INDEX idx_v_block_spatial_cutb_seq_nbr ON LRM_REPLICATION.V_BLOCK_SPATIAL (CUTB_SEQ_NBR);
CREATE INDEX idx_v_block_licn_seq_nbr ON LRM_REPLICATION.V_BLOCK (LICN_SEQ_NBR);
CREATE INDEX idx_v_license_licn_seq_nbr ON LRM_REPLICATION.V_LICENCE (LICN_SEQ_NBR);
CREATE INDEX idx_v_license_activity_all_licn_seq_nbr ON LRM_REPLICATION.V_LICENCE_ACTIVITY_ALL (LICN_SEQ_NBR);
