-- Create roles for ETL and data consumption
CREATE ROLE BCTS_ETL_ROLE;
CREATE ROLE BCTS_DEV_ROLE;
CREATE ROLE BCTS_DEV_ROLE;
CREATE ROLE BCTS_STAGE_ANALYST_ROLE;
CREATE ROLE BCTS_STAGE_ANALYST_PI_ROLE;
CREATE ROLE BCTS_ANALYST_ROLE;
CREATE ROLE BCTS_ANALYST_PI_ROLE;

-- Create BCTS schemas in ODS
CREATE SCHEMA IF NOT EXISTS lrm_replication;
CREATE SCHEMA IF NOT EXISTS bcts_reporting;
CREATE SCHEMA IF NOT EXISTS bcts_staging;
