-- Table: bcts_staging.licence_issued_advertised_official

DROP TABLE IF EXISTS bcts_staging.licence_issued_advertised_official;

CREATE TABLE bcts_staging.licence_issued_advertised_official
(
    business_area_region_category text COLLATE pg_catalog."default",
    business_area_region text COLLATE pg_catalog."default",
    business_area text COLLATE pg_catalog."default",
    business_area_code character varying(6) COLLATE pg_catalog."default",
    forest_file_id character varying COLLATE pg_catalog."default",
    x_axis_date timestamp without time zone,
    x_axis_fiscal text COLLATE pg_catalog."default",
    x_axis_quarter text COLLATE pg_catalog."default",
    file_type_code character varying COLLATE pg_catalog."default",
    auction_count_all_time_to_report_period_end bigint,
    first_auction_date timestamp without time zone,
    first_auction_fiscal text COLLATE pg_catalog."default",
    first_auction_quarter text COLLATE pg_catalog."default",
    first_bcts_category_code character varying COLLATE pg_catalog."default",
    first_auction_volume numeric,
    first_auction_category_a_and_1_volume numeric,
    first_auction_category_2_and_4_volume numeric,
    first_auction_volume_is_in_report_period numeric,
    first_auction_category_a_and_1_volume_is_in_report_period numeric,
    first_auction_category_2_and_4_volume_is_in_report_period numeric,
    last_auction_date timestamp without time zone,
    last_auction_fiscal text COLLATE pg_catalog."default",
    last_auction_quarter text COLLATE pg_catalog."default",
    last_auction_bcts_category_code character varying COLLATE pg_catalog."default",
    last_auction_volume numeric,
    last_auction_category_a_and_1_volume numeric,
    last_auction_category_2_and_4_volume numeric,
    original_cat_2_and_4_readvertised_cat_a_and_1_volume numeric,
    original_cat_a_and_1_readvertised_cat_2_and_4_volume numeric,
    last_auction_no_sale_rationale text COLLATE pg_catalog."default",
    last_auction_no_sale_volume numeric,
    last_auction_no_sale_category_a_1_volume numeric,
    last_auction_no_sale_category_2_4_volume numeric,
    last_auction_no_sale text COLLATE pg_catalog."default",
    last_auction_no_sale_cat_a text COLLATE pg_catalog."default",
    last_auction_no_sale_cat_2_4 text COLLATE pg_catalog."default",
    issued_licence_legal_effective_date timestamp without time zone,
    issued_licence_legal_effective_fiscal text COLLATE pg_catalog."default",
    issued_licence_legal_effective_quarter text COLLATE pg_catalog."default",
    issued_licence_bcts_category_code character varying COLLATE pg_catalog."default",
    issued_licence_volume numeric,
    category_a_and_1_issued_volume numeric,
    category_2_and_4_issued_volume numeric,
    issued_licence_maximum_value numeric,
    issued_licence_maximum_value_cat_a numeric,
    issued_licence_maximum_value_cat_2_4 numeric,
    issued_licence_client_number character varying COLLATE pg_catalog."default",
    issued_licence_client_name text COLLATE pg_catalog."default",
    issued_in_report_period text COLLATE pg_catalog."default",
    issued_in_report_period_cat_a text COLLATE pg_catalog."default",
    issued_in_report_period_cat_2_4 text COLLATE pg_catalog."default",
    advertised_in_report_period text COLLATE pg_catalog."default",
    fta_file_status character varying COLLATE pg_catalog."default",
    fta_file_status_date timestamp without time zone,
    report_frequency text,
    report_start_date date, 
    report_end_date date,
    fiscal_year integer,
    primary key (report_start_date, report_end_date, report_frequency)

);

