
INSERT INTO ods_data_management.cdc_master_table_list 
VALUES (
    NULL,
    'bctsadmin',
    NULL,               
    'the',
    'NO_SALE_RATIONALE_CODE',               
    'bctsadmin_replication',
    'NO_SALE_RATIONALE_CODE',
    'Y',
    NULL,
    NULL,
    NULL,
    'Y',
    1,
    'N',
    'N',
    NULL,
    'Oracle'
);

INSERT INTO ods_data_management.cdc_master_table_list 
VALUES (
    NULL,
    'bctsadmin',
    NULL,               
    'the',
    'BCTS_TENURE_BIDDER',               
    'bctsadmin_replication',
    'BCTS_TENURE_BIDDER',
    'Y',
    NULL,
    NULL,
    NULL,
    'Y',
    1,
    'N',
    'Y',
    'SELECT client_number, 
        forest_file_id, 
        auction_date, 
        bonus_bid, 
        bonus_offer, 
        deposit_amount, 
        bid_deposit_type_code, 
        ineligible_ind, 
        ineligibility_comments, 
        sale_awarded_ind, 
        deposit_returned_ind, 
        nmbr_months_of_registration, 
        NULL AS completed_forest_file_id, 
        NULL AS completed_file_status_date, 
        NULL AS completed_file_type_code, 
        NULL AS issued_forest_file_id, 
        NULL AS issued_file_status_date, 
        NULL AS issued_file_type_code, 
        deposit_level_code, 
        primary_rqmt_met_ind, 
        financial_rqmt_met_ind, 
        ''REDACTED'' AS primary_rqmt_met_comment, 
        ''REDACTED'' AS financial_rqmt_met_comment, 
        ''REDACTED'' AS deposit_level_comment, 
        electronic_bid_ind, 
        update_timestamp, 
        update_userid
	FROM the.bcts_tenure_bidder',
    'Oracle'
);


INSERT INTO ods_data_management.cdc_master_table_list 
VALUES (
    NULL,
    'bctsadmin',
    NULL,               
    'the',
    'BCTS_TIMBER_SALE',               
    'bctsadmin_replication',
    'BCTS_TIMBER_SALE',
    'Y',
    NULL,
    NULL,
    NULL,
    'Y',
    1,
    'N',
    'Y',
    'SELECT forest_file_id, 
        auction_date, 
        bcts_category_code, 
        bcts_rate_code, 
        bcts_silv_obligation_code, 
        lump_sum_category_code, 
        no_sale_rationale_code, 
        sale_location, 
        sale_volume, 
        upset_rate, 
        total_upset_value, 
        deposit_amount, 
        sale_time, 
        decked_timber_ind, 
        lump_sum_ind, 
        ''REDACTED'' AS timber_sale_comment, 
        approved_by, 
        date_approved, 
        legal_effective_date, 
        update_userid, 
        update_timestamp, 
        third_party_deposit_name, 
        third_party_deposit_ind
	FROM the.bcts_timber_sale',
    'Oracle'
);

